"""
Report Exporter — Multi-Format Compliance Report Export
---------------------------------------------------------
Takes the Markdown report generated by Agent 5 (agent5_report_generation.py)
and exports it to additional formats: HTML, JSON, and plain text.

Usage:
    python report_exporter.py --framework nist/csf --format html
    python report_exporter.py --framework eu/gdpr --format json
    python report_exporter.py --framework india/dpdp --format txt

    # Export all formats at once
    python report_exporter.py --framework nist/csf --format all

This module does NOT modify agent5_report_generation.py — it reads existing
Markdown reports and converts them.
"""

import os
import re
import sys
import json
import glob
import argparse
from datetime import datetime

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
except ImportError:
    canvas = None
    colors = None

# Ensure project root is importable
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)


REPORTS_DIR = "reports"


# ---------------------------------------------------------------------------
# Markdown -> HTML
# ---------------------------------------------------------------------------
HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg: #0a0e1a;
            --surface: #111827;
            --border: #1e293b;
            --text: #e2e8f0;
            --accent: #818cf8;
            --success: #34d399;
            --warning: #fbbf24;
            --danger: #f87171;
            --muted: #94a3b8;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', 'Inter', system-ui, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.7;
            padding: 2rem;
            max-width: 1000px;
            margin: 0 auto;
        }}
        h1 {{
            color: var(--accent);
            font-size: 2rem;
            margin-bottom: 1rem;
            border-bottom: 2px solid var(--border);
            padding-bottom: 0.5rem;
        }}
        h2 {{
            color: var(--accent);
            font-size: 1.4rem;
            margin-top: 2rem;
            margin-bottom: 0.8rem;
        }}
        h3 {{
            color: var(--text);
            font-size: 1.1rem;
            margin-top: 1.5rem;
            margin-bottom: 0.5rem;
        }}
        p, li {{
            margin-bottom: 0.5rem;
        }}
        strong {{
            color: #f1f5f9;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            background: var(--surface);
            border-radius: 8px;
            overflow: hidden;
        }}
        th, td {{
            padding: 0.75rem 1rem;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }}
        th {{
            background: rgba(129, 140, 248, 0.1);
            color: var(--accent);
            font-weight: 600;
        }}
        hr {{
            border: none;
            border-top: 1px solid var(--border);
            margin: 1.5rem 0;
        }}
        code {{
            background: var(--surface);
            padding: 0.15rem 0.4rem;
            border-radius: 4px;
            font-size: 0.9em;
        }}
        ul {{
            padding-left: 1.5rem;
        }}
        .footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border);
            color: var(--muted);
            font-size: 0.85rem;
            font-style: italic;
        }}
    </style>
</head>
<body>
{body}
<div class="footer">
    Exported on {export_date} by ComplianceMesh Report Exporter
</div>
</body>
</html>
"""


def markdown_to_html(md_content: str) -> str:
    """
    Converts Markdown to HTML using simple regex-based transformation.
    Handles: headings, bold, tables, horizontal rules, lists, code, and paragraphs.
    """
    lines = md_content.split("\n")
    html_lines = []
    in_table = False
    in_list = False

    for line in lines:
        stripped = line.strip()

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            if in_table:
                html_lines.append("</table>")
                in_table = False
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<hr>")
            continue

        # Table separator row (|---|---|)
        if re.match(r"^\|[-:|]+\|$", stripped):
            continue

        # Table row
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.split("|")[1:-1]]
            if not in_table:
                html_lines.append("<table>")
                in_table = True
                # First row is header
                html_lines.append("<tr>" + "".join(f"<th>{_inline_md(c)}</th>" for c in cells) + "</tr>")
            else:
                html_lines.append("<tr>" + "".join(f"<td>{_inline_md(c)}</td>" for c in cells) + "</tr>")
            continue

        if in_table and not stripped.startswith("|"):
            html_lines.append("</table>")
            in_table = False

        # Headings
        if stripped.startswith("### "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h3>{_inline_md(stripped[4:])}</h3>")
            continue
        if stripped.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h2>{_inline_md(stripped[3:])}</h2>")
            continue
        if stripped.startswith("# "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h1>{_inline_md(stripped[2:])}</h1>")
            continue

        # List items
        if stripped.startswith("- "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{_inline_md(stripped[2:])}</li>")
            continue

        if in_list and stripped and not stripped.startswith("- "):
            html_lines.append("</ul>")
            in_list = False

        # Paragraph
        if stripped:
            html_lines.append(f"<p>{_inline_md(stripped)}</p>")

    if in_table:
        html_lines.append("</table>")
    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Converts inline Markdown (bold, code, links) to HTML."""
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Inline code
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    return text


# ---------------------------------------------------------------------------
# Markdown -> JSON
# ---------------------------------------------------------------------------
def markdown_to_json(md_content: str, jurisdiction: str, framework: str) -> dict:
    """
    Parses the Markdown report into a structured JSON representation.
    """
    sections = re.split(r"\n## ", md_content)

    result = {
        "jurisdiction": jurisdiction,
        "framework": framework,
        "export_format": "json",
        "exported_at": datetime.now().isoformat(),
        "sections": {},
    }

    for section in sections:
        lines = section.strip().split("\n")
        if not lines:
            continue
        title = lines[0].strip().lstrip("# ").strip()
        content = "\n".join(lines[1:]).strip()
        result["sections"][title] = content

    return result


# ---------------------------------------------------------------------------
# Markdown -> Plain Text
# ---------------------------------------------------------------------------
def markdown_to_text(md_content: str) -> str:
    """Strips Markdown formatting for plain-text email-friendly output."""
    text = md_content
    # Remove heading markers
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Remove bold markers
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    # Remove inline code markers
    text = re.sub(r"`(.+?)`", r"\1", text)
    # Remove table formatting (keep content)
    text = re.sub(r"^\|[-:|]+\|$", "", text, flags=re.MULTILINE)
    text = re.sub(r"\|", "  ", text)
    # Remove horizontal rules
    text = re.sub(r"^---+$", "-" * 60, text, flags=re.MULTILINE)
    return text.strip()


# ---------------------------------------------------------------------------
# Export orchestration
# ---------------------------------------------------------------------------
def find_latest_report(jurisdiction: str, framework: str) -> str | None:
    """Finds the most recent Markdown report for the given jurisdiction/framework."""
    pattern = os.path.join(REPORTS_DIR, f"{jurisdiction}__{framework}_report_*.md")
    reports = sorted(glob.glob(pattern))
    if reports:
        return reports[-1]  # most recent by timestamp in filename
    return None


def strip_all_markdown_and_emojis(text: str) -> str:
    """
    Strips all emojis, decorative symbols, and markdown markup
    (e.g., **, *, `, #, list markers, [link](url)) from text.
    """
    if not text:
        return ""
    emoji_pattern = re.compile(
        r'[\U00010000-\U0010ffff]|[\u2600-\u27bf]|[\u2300-\u23ff]|[\u2b50-\u2b55]|[\u200d\ufe0f\u20e3]|'
        r'[✅⚠️❌⛔🔹🔸▪️•💻⚪🐙🔍📊📘📄📑📕]',
        flags=re.UNICODE
    )
    cleaned = emoji_pattern.sub('', text)
    cleaned = re.sub(r'\*{1,3}', '', cleaned)
    cleaned = re.sub(r'_{1,3}', '', cleaned)
    cleaned = re.sub(r'`+', '', cleaned)
    cleaned = re.sub(r'#{1,6}\s*', '', cleaned)
    cleaned = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', cleaned)
    cleaned = re.sub(r'^\s*[-*•]\s*', '', cleaned)
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()
    return cleaned


FRAMEWORK_DISPLAY_NAMES = {
    # NIST CSF
    "csf": "NIST Cybersecurity Framework 2.0 (CSF 2.0)",
    "nist_csf": "NIST Cybersecurity Framework 2.0 (CSF 2.0)",
    "csf_2_0": "NIST Cybersecurity Framework 2.0 (CSF 2.0)",
    "csf2": "NIST Cybersecurity Framework 2.0 (CSF 2.0)",
    
    # NIST SP 800-63B
    "sp_800_63b_r4": "NIST SP 800-63B Authentication & Lifecycle (Rev 4)",
    "sp_800_63b": "NIST SP 800-63B Authentication & Lifecycle (Rev 4)",
    "nist_800_63b": "NIST SP 800-63B Authentication & Lifecycle (Rev 4)",
    "nist_sp_800_63b": "NIST SP 800-63B Authentication & Lifecycle (Rev 4)",
    "nist_sp_800_63b_r4": "NIST SP 800-63B Authentication & Lifecycle (Rev 4)",
    "800_63b": "NIST SP 800-63B Authentication & Lifecycle (Rev 4)",
    "800_63b_r4": "NIST SP 800-63B Authentication & Lifecycle (Rev 4)",

    # NIST SP 800-53
    "nist_sp_800_53": "NIST SP 800-53 Rev 5 Security & Privacy Controls",
    "us_nist_sp_800_53": "NIST SP 800-53 Rev 5 Security & Privacy Controls",
    "sp_800_53": "NIST SP 800-53 Rev 5 Security & Privacy Controls",
    "800_53": "NIST SP 800-53 Rev 5 Security & Privacy Controls",
    "nist_800_53": "NIST SP 800-53 Rev 5 Security & Privacy Controls",

    # NIST Cloud / Zero Trust / IoT / AI RMF
    "cloud": "NIST SP 800-145 Cloud Computing Standards",
    "nist_cloud": "NIST SP 800-145 Cloud Computing Standards",
    "sp_800_145": "NIST SP 800-145 Cloud Computing Standards",
    "zero_trust": "NIST SP 800-207 Zero Trust Architecture",
    "nist_zero_trust": "NIST SP 800-207 Zero Trust Architecture",
    "sp_800_207": "NIST SP 800-207 Zero Trust Architecture",
    "iot": "NIST SP 800-213 IoT Device Cybersecurity Guidance",
    "nist_iot": "NIST SP 800-213 IoT Device Cybersecurity Guidance",
    "sp_800_213": "NIST SP 800-213 IoT Device Cybersecurity Guidance",
    "ai_rmf": "NIST AI Risk Management Framework 1.0 (AI RMF)",
    "nist_ai_rmf": "NIST AI Risk Management Framework 1.0 (AI RMF)",
    "us_nist_ai_rmf": "NIST AI Risk Management Framework 1.0 (AI RMF)",

    # EU Frameworks
    "gdpr": "EU General Data Protection Regulation (GDPR)",
    "eu_gdpr": "EU General Data Protection Regulation (GDPR)",
    "nis2": "EU NIS2 Directive (2022/2555)",
    "eu_nis2": "EU NIS2 Directive (2022/2555)",
    "dora": "Digital Operational Resilience Act (EU DORA)",
    "eu_dora": "Digital Operational Resilience Act (EU DORA)",
    "ai_act": "EU Artificial Intelligence Act (EU AI Act)",
    "eu_ai_act": "EU Artificial Intelligence Act (EU AI Act)",

    # India Frameworks
    "dpdp": "India Digital Personal Data Protection Act (DPDP 2023)",
    "india_dpdp": "India Digital Personal Data Protection Act (DPDP 2023)",
    "cert_in": "India CERT-In Directives (2022/68)",
    "india_cert_in": "India CERT-In Directives (2022/68)",

    # International
    "iso27001": "ISO/IEC 27001:2022 ISMS",
    "iso_27001": "ISO/IEC 27001:2022 ISMS",
    "international_iso27001": "ISO/IEC 27001:2022 ISMS",
    "iso": "ISO/IEC 27001:2022 ISMS",

    # US / Industry Standards
    "hipaa": "US HIPAA Security & Privacy Rule",
    "us_hipaa": "US HIPAA Security & Privacy Rule",
    "pci_dss": "PCI-DSS v4.0.1",
    "pci_dss_v4": "PCI-DSS v4.0.1",
    "us_pci_dss_v4": "PCI-DSS v4.0.1",
    "pci": "PCI-DSS v4.0.1",
    "soc2": "AICPA SOC 2 Type II",
    "us_soc2": "AICPA SOC 2 Type II",
    "cisa_cpg": "CISA Cross-Sector Cybersecurity Performance Goals",
    "us_cisa_cpg": "CISA Cross-Sector Cybersecurity Performance Goals",

    # OWASP
    "owasp_asvs": "OWASP Application Security Verification Standard (ASVS v5.0)",
    "asvs": "OWASP Application Security Verification Standard (ASVS v5.0)",
    "asvs_v5": "OWASP Application Security Verification Standard (ASVS v5.0)",
    "owasp_asvs_v5": "OWASP Application Security Verification Standard (ASVS v5.0)",
    "owasp_wstg": "OWASP Web Security Testing Guide (WSTG v4.2)",
    "wstg_v42": "OWASP Web Security Testing Guide (WSTG v4.2)",
    "owasp_wstg_v42": "OWASP Web Security Testing Guide (WSTG v4.2)",
    "top10_web": "OWASP Top 10 Web Application Security Risks",
    "owasp_top10_web": "OWASP Top 10 Web Application Security Risks",
    "llm_top10": "OWASP Top 10 for LLM Applications",
    "owasp_llm_top10": "OWASP Top 10 for LLM Applications",
    "masvs": "OWASP Mobile Application Security Verification Standard",
    "owasp_masvs": "OWASP Mobile Application Security Verification Standard",

    # CIS / MITRE / CWE
    "cwe": "CWE Top 25 Most Dangerous Software Weaknesses",
    "cwe_v4": "CWE Top 25 Most Dangerous Software Weaknesses",
    "cwe_top25": "CWE Top 25 Most Dangerous Software Weaknesses",
    "aws_foundations": "CIS AWS Foundations Benchmark v3.0",
    "cis_aws_foundations": "CIS AWS Foundations Benchmark v3.0",
    "k8s": "CIS Kubernetes Benchmark v1.8",
    "cis_k8s": "CIS Kubernetes Benchmark v1.8",
    "atlas": "MITRE ATLAS (AI Threat Landscape)",
    "mitre_atlas": "MITRE ATLAS (AI Threat Landscape)",
    "attack": "MITRE ATT&CK Enterprise Matrix",
    "mitre_attack": "MITRE ATT&CK Enterprise Matrix",
}


def resolve_canonical_framework_name(md_content: str = "", jurisdiction: str = None, framework: str = None) -> str:
    """
    Accurately resolves the formal framework display name.
    Prioritizes explicit headers in markdown report content over generic defaults.
    """
    def _match_key(candidate: str) -> str | None:
        if not candidate:
            return None
        c_clean = candidate.strip().strip("`").strip("*").strip()
        # Strip trailing jurisdiction tag in parentheses e.g. "ISO_27001 (INTERNATIONAL)" -> "ISO_27001"
        c_no_paren = re.sub(r'\s*\([A-Za-z0-9_\-/\. ]+\)\s*$', '', c_clean).strip()
        norm_key = re.sub(r'[^a-z0-9]', '_', c_no_paren.lower()).strip('_')
        if norm_key in FRAMEWORK_DISPLAY_NAMES:
            return FRAMEWORK_DISPLAY_NAMES[norm_key]
        
        norm_raw = re.sub(r'[^a-z0-9]', '_', c_clean.lower()).strip('_')
        if norm_raw in FRAMEWORK_DISPLAY_NAMES:
            return FRAMEWORK_DISPLAY_NAMES[norm_raw]

        for k, disp in FRAMEWORK_DISPLAY_NAMES.items():
            if k == norm_key or (len(k) >= 4 and (k in norm_key or norm_key in k)):
                return disp
        return None

    # 1. Step 1: Scan md_content for explicit metadata headers
    if md_content:
        patterns = [
            r'(?:^|\n|\|)\s*(?:\*\*|#+)?\s*(?:Target Framework Benchmark|Target Framework|Framework Benchmark|Regulatory Standard\s*/\s*Framework|Regulatory Standard|Target Regulatory Standard|Standard\s*/\s*Framework|Benchmark|Framework|Standard)\s*[:—–-]\s*[\*`]?([^\n`*|]+)[\*`]?',
            r'(?:^|\n)\s*\|\s*(?:\*\*)?(?:Regulatory Standard\s*/\s*Framework|Regulatory Standard|Framework|Benchmark)(?:\*\*)?\s*\|\s*([^|\n]+)\|',
            r'(?:^|\n)\s*#+\s*(?:Compliance\s+)?(?:Audit\s+)?Report\s*[—–-]\s*([^\n]+)',
            r'(?:^|\n)\s*##\s*Framework:\s*([^\n]+)',
            r'against\s+the\s+[`\*]?([A-Za-z0-9_\-/\. ]+?)[`\*]?\s*(?:\([A-Za-z0-9_\-/\. ]+\)\s*)?regulatory\s+framework',
            r'####\s*Compliance\s*(?:Summary|Breakdown|Status Matrix)\s*\(([^)]+)\)',
        ]
        for p in patterns:
            m = re.search(p, md_content, re.IGNORECASE)
            if m:
                raw_val = m.group(1).strip()
                if raw_val and len(raw_val) <= 80 and not any(w in raw_val.lower() for w in ["obligation", "like those", "outlined in", "section", "status", "scorecard", "breakdown"]):
                    disp = _match_key(raw_val)
                    if disp:
                        return disp
                    if "/" in raw_val or "—" in raw_val or "-" in raw_val:
                        parts = re.split(r'[/—–-]', raw_val)
                        for part in parts:
                            d_p = _match_key(part)
                            if d_p:
                                return d_p
                    if len(raw_val) >= 3 and raw_val.lower() not in ("csf", "compliance", "compliance_audit", "auto-detect", "auto-detect (smart route)", "standard"):
                        return raw_val.strip("`* ").replace("_", " ").upper()

    # 2. Step 2: Check explicit framework argument if provided and non-generic
    if framework:
        fw_clean = framework.strip().lower()
        if fw_clean not in ("", "none", "csf", "compliance", "compliance_audit", "auto-detect", "auto-detect (smart route)", "standard", "unknown"):
            disp = _match_key(framework)
            if disp:
                return disp
            if jurisdiction:
                disp_jur = _match_key(f"{jurisdiction}_{framework}")
                if disp_jur:
                    return disp_jur
            return framework.replace("_", " ").upper()

    # 3. Step 3: Check md_content for prominent mentions of specific frameworks
    if md_content:
        content_lower = md_content.lower()
        keyword_map = [
            ("iso 27001", "ISO/IEC 27001:2022 ISMS"),
            ("iso27001", "ISO/IEC 27001:2022 ISMS"),
            ("iso/iec 27001", "ISO/IEC 27001:2022 ISMS"),
            ("gdpr", "EU General Data Protection Regulation (GDPR)"),
            ("nis2", "EU NIS2 Directive (2022/2555)"),
            ("dora", "Digital Operational Resilience Act (EU DORA)"),
            ("ai act", "EU Artificial Intelligence Act (EU AI Act)"),
            ("dpdp", "India Digital Personal Data Protection Act (DPDP 2023)"),
            ("cert-in", "India CERT-In Directives (2022/68)"),
            ("cert_in", "India CERT-In Directives (2022/68)"),
            ("hipaa", "US HIPAA Security & Privacy Rule"),
            ("pci-dss", "PCI-DSS v4.0.1"),
            ("pci_dss", "PCI-DSS v4.0.1"),
            ("pci dss", "PCI-DSS v4.0.1"),
            ("soc 2", "AICPA SOC 2 Type II"),
            ("soc2", "AICPA SOC 2 Type II"),
            ("asvs", "OWASP Application Security Verification Standard (ASVS v5.0)"),
            ("sp 800-63b", "NIST SP 800-63B Authentication & Lifecycle (Rev 4)"),
            ("sp_800_63b", "NIST SP 800-63B Authentication & Lifecycle (Rev 4)"),
            ("800-63b", "NIST SP 800-63B Authentication & Lifecycle (Rev 4)"),
            ("800_63b", "NIST SP 800-63B Authentication & Lifecycle (Rev 4)"),
            ("sp 800-53", "NIST SP 800-53 Rev 5 Security & Privacy Controls"),
            ("ai rmf", "NIST AI Risk Management Framework 1.0 (AI RMF)"),
            ("cisa cpg", "CISA Cross-Sector Cybersecurity Performance Goals"),
            ("cwe", "CWE Top 25 Most Dangerous Software Weaknesses"),
            ("aws foundations", "CIS AWS Foundations Benchmark v3.0"),
            ("kubernetes benchmark", "CIS Kubernetes Benchmark v1.8"),
        ]
        for kw, disp in keyword_map:
            if kw in content_lower:
                return disp

    # 4. Final fallback
    if framework and framework.lower() not in ("", "none", "compliance", "compliance_audit", "auto-detect", "auto-detect (smart route)"):
        disp = _match_key(framework)
        if disp:
            return disp
        return framework.replace("_", " ").upper()

    return "NIST Cybersecurity Framework 2.0 (CSF 2.0)"


def is_control_heading(line: str) -> bool:
    """Returns True if the line represents an actual control item header."""
    s = line.strip()
    if s.startswith(("🔹", "🔸", "#### 🔹", "### 🔹", "- 🔹", "* 🔹")):
        return True
    if s.startswith("#### `") or s.startswith("### `"):
        return True
    if s.startswith("#### ") and any(sep in s for sep in ["—", "–", " - "]):
        clean = strip_all_markdown_and_emojis(s).lower()
        if not any(k in clean for k in ["compliance breakdown", "scorecard", "summary", "action required"]):
            return True
    return False


def extract_canonical_control_id(raw_text: str) -> str:
    """
    STRICT CONTROL ID EXTRACTOR:
    Extracts ONLY the formal statutory or technical control identifier
    (e.g., Recital 91, Article 32, 34.3.a, 6.3.257, PR.AC-1, ID.GV-1, A.8.1, REQ-01, CWE-89).
    """
    cleaned = strip_all_markdown_and_emojis(raw_text).strip()
    
    if '—' in cleaned:
        cleaned = cleaned.split('—')[0].strip()
    elif '–' in cleaned:
        cleaned = cleaned.split('–')[0].strip()
    elif ':' in cleaned and not cleaned.lower().startswith(('http:', 'https:')):
        cleaned = cleaned.split(':')[0].strip()
        
    cleaned = cleaned.strip(' \t`*')
    
    patterns = [
        r'\b(NIST\s+SP\s+800-\d+\s+[A-Z]{2}-\d+)\b',
        r'\b(SP_800_63B_R4-REQ-\d+)\b',
        r'\b([A-Z]{2,4}\.[A-Z]{2,4}-\d+(?:\.\d+)?)\b',
        r'\b(Recital\s+\d+)\b',
        r'\b(Article\s+[\d\.]+(?:\([a-z0-9]+\))?)\b',
        r'\b(Art\.?\s*[\d\.]+(?:\([a-z0-9]+\))?)\b',
        r'\b(Preambule\.?\d*)\b',
        r'\b(WSTG-[A-Z]+-\d+)\b',
        r'\b([A-Z]\.\d+\.\d+(?:\.\d+)?)\b',
        r'\b(REQ-\d+)\b',
        r'\b(CWE-\d+)\b',
        r'\b(ASVS-[A-Za-z0-9\.\-]+)\b',
        r'\b(\d+\.\d+(?:\.[a-z0-9]+)?(?:\.[a-z0-9]+)?)\b',
        r'\b(GAP-\d+)\b',
        r'\b([A-Z]{2,4}-\d+)\b'
    ]
    for p in patterns:
        m = re.search(p, cleaned, re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return cleaned[:30]


def extract_audit_findings_matrix(md_content: str, jurisdiction: str = "nist", framework: str = "csf") -> list[dict]:
    """
    Extracts structured findings into a canonical list of 6-field dictionaries:
    [control_id, title, status, rationale, remediation, priority]
    Handles section-grouped findings, runtime probes, markdown tables, and headings.
    """
    raw_lines = md_content.split('\n')
    findings = []

    # Strategy 1: Section-grouped Headings & Bullet items
    current_section_status = None
    lines = md_content.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        clean_line = line.lstrip('#').strip().lower()
        
        is_section_header = (
            (line.startswith('#') or clean_line.endswith('controls:') or clean_line.endswith('controls'))
            and not clean_line.startswith(('*', '-', '•', '`', '🔹', '🔸'))
            and any(k in clean_line for k in ['control', 'matrix', 'finding', 'gap', 'scope', 'compliant'])
        )
        
        if is_section_header:
            if any(w in clean_line for w in ['not compliant', 'non-compliant', 'gaps / not compliant', 'gaps']):
                current_section_status = 'Not Compliant'
            elif any(w in clean_line for w in ['partially compliant', 'partial']):
                current_section_status = 'Partially Compliant'
            elif any(w in clean_line for w in ['fully compliant', 'compliant']) and not any(w in clean_line for w in ['not', 'non', 'gap']):
                current_section_status = 'Fully Compliant'
            elif any(w in clean_line for w in ['evaluated scope', 'not applicable', 'pre-implementation']):
                current_section_status = 'Not Applicable'

        if is_control_heading(line):
            raw_heading = re.sub(r'^[#\-\*\s🔹🔸]+', '', line).strip()
            cid = extract_canonical_control_id(raw_heading)
            
            # Extract title
            title_part = ''
            if '—' in raw_heading:
                title_part = raw_heading.split('—', 1)[1].strip()
            elif '–' in raw_heading:
                title_part = raw_heading.split('–', 1)[1].strip()
            elif ':' in raw_heading and not raw_heading.startswith(('http:', 'https:')):
                title_part = raw_heading.split(':', 1)[1].strip()
            else:
                title_part = raw_heading
            clean_title = strip_all_markdown_and_emojis(title_part)
            
            body_lines = []
            j = i + 1
            while j < len(lines):
                nxt = lines[j].strip()
                if is_control_heading(nxt) or (nxt.startswith(('### ', '## ')) and not nxt.startswith('####')) or nxt.startswith('---') or (nxt.lower().endswith('controls:') and any(k in nxt.lower() for k in ['compliant', 'gaps', 'not compliant'])):
                    break
                body_lines.append(nxt)
                j += 1
            body_text = '\n'.join(body_lines)

            # A control-level status is authoritative
            m_status = re.search(r'(?:^|\n)\s*(?:-\s*)?(?:\*\*)?Status(?:\*\*)?:\s*([^\n]+)', body_text, re.IGNORECASE)
            item_status = strip_all_markdown_and_emojis(m_status.group(1)) if m_status else (current_section_status or 'No Evidence Found')

            # Rationale extraction (supports both sub-bullets and multi-line plain text blocks)
            rationale_parts = []
            audit_bullets = re.findall(r'(?:^|\n)\s*(?:[-*]\s*)?(?:\*\*)?(?:Audit Finding|Control Requirement|Potential Risks|Technical Restrictions|Evidence & Scan Details|Auditor Explanation|Rationale|Detail)(?:\*\*)?:\s*([^\n]+)', body_text, re.IGNORECASE)
            if audit_bullets:
                rationale_parts.extend([strip_all_markdown_and_emojis(b) for b in audit_bullets if strip_all_markdown_and_emojis(b)])
            
            if not rationale_parts:
                m_exp = re.search(r'(?:^|\n)\s*(?:[-*]\s*)?(?:\*\*)?(?:Auditor Explanation|Rationale|Explanation|Detail)(?:\*\*)?:\s*([\s\S]+?)(?=\n\s*(?:-\s*)?(?:\*\*)?(?:Client Remediation|Remediation|Evidence Source|Status)|\Z)', body_text, re.IGNORECASE)
                if m_exp:
                    rationale_parts.append(strip_all_markdown_and_emojis(m_exp.group(1)))

            rationale = ' '.join(rationale_parts) if rationale_parts else f'Evaluated safeguard requirement for {clean_title}.'

            # Remediation extraction
            m_rem = re.search(r'(?:^|\n)\s*(?:[-*]\s*)?(?:\*\*)?(?:Client Remediation Plan|Recommended Remediation|Remediation|Recommendation)(?:\*\*)?:\s*([\s\S]+?)(?=\n\s*(?:-\s*)?(?:\*\*)?(?:Evidence Source|Status)|\Z)', body_text, re.IGNORECASE)
            if m_rem:
                rem_raw = m_rem.group(1).strip()
                rem_bullets = re.findall(r'\*\s*([^\n]+)', rem_raw)
                if rem_bullets:
                    remediation = ' '.join([strip_all_markdown_and_emojis(b) for b in rem_bullets if strip_all_markdown_and_emojis(b)])
                else:
                    remediation = strip_all_markdown_and_emojis(rem_raw)
            else:
                remediation = 'Maintain verified baseline.' if item_status == 'Fully Compliant' else 'Implement required safeguards to achieve compliance.'

            findings.append({
                'control_id': cid,
                'title': clean_title,
                'status': item_status,
                'rationale': rationale,
                'remediation': remediation
            })
            i = j - 1

        elif line.startswith(('- **', '* **')) and ('—' in line or '–' in line) and ':' in line:
            m_probe = re.match(r'^[-*]\s*\*\*([A-Za-z0-9_\.\-]+)\s*[—–-]\s*([^\*]+)\*\*:\s*([^\n]+)', line)
            if m_probe:
                p_cid = extract_canonical_control_id(m_probe.group(1))
                p_title = strip_all_markdown_and_emojis(m_probe.group(2))
                p_status_raw = m_probe.group(3).strip()
                status_val = 'Not Compliant' if 'fail' in p_status_raw.lower() else ('Untested' if any(w in p_status_raw.lower() for w in ['untested', 'nodata', 'no_data']) else 'Compliant')
                
                findings.append({
                    'control_id': p_cid,
                    'title': p_title,
                    'status': status_val,
                    'rationale': f'Runtime probe status: {strip_all_markdown_and_emojis(p_status_raw)}',
                    'remediation': 'Address dynamic probe finding.' if status_val != 'Compliant' else 'Probe passed.'
                })

        i += 1

    # Strategy 2: Table-based Findings Matrix
    if not findings:
        table_lines = [l.strip() for l in raw_lines if l.strip().startswith('|') and l.strip().endswith('|')]
        if len(table_lines) > 2:
            rows = [t for t in table_lines if not re.match(r'^\|[-:| ]+\|$', t)]
            if len(rows) > 1:
                header_cells = [c.strip().lower() for c in rows[0].split('|')[1:-1]]
                id_idx = next((idx_h for idx_h, h in enumerate(header_cells) if any(k in h for k in ['id', 'req', 'control'])), 0)
                title_idx = next((idx_h for idx_h, h in enumerate(header_cells) if any(k in h for k in ['design', 'title', 'requirement', 'description', 'name'])), 1 if len(header_cells) > 1 else 0)
                status_idx = next((idx_h for idx_h, h in enumerate(header_cells) if 'status' in h), -1)
                rem_idx = next((idx_h for idx_h, h in enumerate(header_cells) if any(k in h for k in ['remediation', 'action', 'recommendation'])), -1)

                for row in rows[1:]:
                    cells = [c.strip() for c in row.split('|')[1:-1]]
                    if len(cells) < 2:
                        continue
                    first_cell_clean = re.sub(r'[^\w\s]', '', cells[0]).strip().lower()
                    if any(first_cell_clean.startswith(w) for w in ['compliant', 'fully compliant', 'partially', 'not compliant', 'non compliant', 'not applicable', 'no evidence', 'total', 'control status', 'status', 'summary']):
                        continue

                    raw_id = cells[id_idx].strip() if id_idx < len(cells) else f"CTRL-{len(findings)+1}"
                    clean_id = extract_canonical_control_id(raw_id)
                    raw_title = strip_all_markdown_and_emojis(cells[title_idx]) if title_idx < len(cells) else "Security Requirement"
                    clean_title = re.sub(rf'^{re.escape(clean_id)}\s*[—–-]?\s*', '', raw_title, flags=re.IGNORECASE).strip() or raw_title
                    status_text = strip_all_markdown_and_emojis(cells[status_idx]) if (status_idx != -1 and status_idx < len(cells)) else "Evaluated"

                    st_low = status_text.lower()
                    rem_text = strip_all_markdown_and_emojis(cells[rem_idx]) if (rem_idx != -1 and rem_idx < len(cells)) else ("Implement missing safeguard controls to achieve full compliance." if "compliant" not in st_low or "not" in st_low else "Maintain verified operational baseline.")

                    findings.append({
                        "control_id": clean_id,
                        "title": clean_title,
                        "status": status_text,
                        "rationale": f"Evaluated compliance baseline for {clean_title}.",
                        "remediation": rem_text
                    })

    # Strategy 3: Standard ### Headings
    if not findings:
        finding_blocks = re.findall(r'#{2,4}\s*([A-Za-z0-9_\.\-]+(?:\s*—\s*[^\n]+)?)\s*\n([\s\S]+?)(?=\n#{2,4}|\n---|\Z)', md_content)
        for title_line, body in finding_blocks:
            if any(w in title_line.lower() for w in ['executive summary', 'summary of findings', 'recommendation', 'auditor sign-off', 'actionable', 'control mapping', 'summary']):
                continue
            raw_id = title_line.split('—')[0].strip() if '—' in title_line else title_line.strip()
            clean_id = extract_canonical_control_id(raw_id)
            raw_title = strip_all_markdown_and_emojis(title_line.split('—')[1].strip() if '—' in title_line else "Control Safeguard")

            status = "Compliant"
            m_st = re.search(r'-\s*\*\*Status\*\*:\s*([^\n]+)', body, re.IGNORECASE)
            if m_st:
                status = strip_all_markdown_and_emojis(m_st.group(1))

            rationale = "Safeguard controls evaluated against standard baseline."
            m_exp = re.search(r'-\s*\*\*(?:Rationale|Auditor Explanation|Details|Explanation):\*\*\s*([\s\S]+?)(?=\n\s*-\s*\*\*|\Z)', body, re.IGNORECASE)
            if m_exp:
                rationale = strip_all_markdown_and_emojis(m_exp.group(1))

            remediation = "Maintain verified baseline." if "Compliant" in status and "Not" not in status else "Implement required safeguards."
            m_rem = re.search(r'-\s*\*\*(?:Recommended remediation|Remediation|Recommendation|Client Remediation Plan):\*\*\s*([\s\S]+?)(?=\n\s*-\s*\*\*|\Z)', body, re.IGNORECASE)
            if m_rem:
                remediation = strip_all_markdown_and_emojis(m_rem.group(1))

            findings.append({
                "control_id": clean_id,
                "title": raw_title,
                "status": status,
                "rationale": rationale,
                "remediation": remediation
            })

    try:
        import report_sanitizer
        findings = report_sanitizer.sanitize_assessment_batch(findings, framework=f"{jurisdiction}/{framework}")
    except Exception:
        pass

    return findings


def build_comprehensive_executive_summary(md_content: str, detected_client: str, detected_fw: str, findings: list[dict]) -> str:
    """
    Constructs a rich, publication-grade Executive Summary synthesizing
    the audit scope, scorecard breakdown, and key operational observations.
    """
    m_exec = re.search(r'(?:#{1,4}\s*Executive Summary|\*\*Executive Summary\*\*)\s*\n+([\s\S]+?)(?:\n#{1,4}|\n---|\Z)', md_content, re.IGNORECASE)
    raw_summary = m_exec.group(1).strip() if m_exec else ""
    clean_summary = strip_all_markdown_and_emojis(raw_summary)

    # If the report already contains a detailed multi-sentence summary (> 140 chars), return it
    if len(clean_summary) > 140 and not clean_summary.startswith("Automated compliance assessment completed"):
        return clean_summary

    cnt_f = sum(1 for f in findings if 'Fully' in f.get('status', ''))
    cnt_p = sum(1 for f in findings if 'Partially' in f.get('status', ''))
    cnt_n = sum(1 for f in findings if 'Not' in f.get('status', ''))
    cnt_na = sum(1 for f in findings if any(k in f.get('status', '').lower() for k in ['applicable', 'untested', 'pre-implementation', 'design']))
    tot_assess = cnt_f + cnt_p + cnt_n
    
    pct_f = f"{(cnt_f / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"
    pct_gaps = f"{((cnt_p + cnt_n) / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"

    p1 = (
        f"This regulatory compliance audit conducted by the ComplianceMesh Multi-Agent Pipeline evaluated the technical evidence, "
        f"configuration architecture, and runtime security posture of {detected_client} against the {detected_fw} framework baseline. "
        f"The scope of assessment encompasses automated code inspection, authentication and authorization safeguards, data protection at rest, "
        f"and dynamic runtime probing."
    )
    p2 = (
        f"Across {tot_assess} assessable technical controls evaluated, {cnt_f} controls ({pct_f}) demonstrated verified compliance with established security criteria. "
        f"A total of {cnt_p + cnt_n} controls ({pct_gaps}) exhibited implementation gaps or insufficient technical evidence in the evaluated scope. "
        f"An additional {cnt_na} control items represent organizational governance, data protection agreements, or procedural workflows requiring administrative review."
    )
    p3 = (
        f"Remediation priorities include formalizing granular role-based authorization beyond administrative flags, enforcing comprehensive audit logging "
        f"for sensitive data operations, and verifying transport-layer encryption configurations. Following the engineering roadmap detailed in this report "
        f"will establish a defensible, audit-ready compliance posture."
    )

    return f"{p1}\n\n{p2}\n\n{p3}"


def render_template_docx_bytes(md_content: str, jurisdiction: str = "nist", framework: str = "csf") -> bytes:
    """
    Renders a professional 5-column Word (.docx) audit document:
    - Table 1: Client Metadata Card (2 columns)
    - Table 2: Executive Compliance Scorecard (3 columns, no emojis)
    - Table 3: 5-Column Technical Control Assessment Matrix
    - Table 4: Actionable Remediation Roadmap & Milestones (3 columns)
    """
    import io
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml import parse_xml
    from docx.oxml.ns import nsdecls

    doc = docx.Document()

    # Landscape layout
    for section in doc.sections:
        section.top_margin = Inches(0.6)
        section.bottom_margin = Inches(0.6)
        section.left_margin = Inches(0.6)
        section.right_margin = Inches(0.6)
        section.orientation = docx.enum.section.WD_ORIENT.LANDSCAPE
        section.page_width = Inches(11.0)
        section.page_height = Inches(8.5)

    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(9.5)
    font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)

    def set_cell_shading(cell, color_hex):
        shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>')
        cell._tc.get_or_add_tcPr().append(shading)

    def set_cell_borders(cell, color_hex="CBD5E1"):
        tcPr = cell._tc.get_or_add_tcPr()
        borders = parse_xml(
            f'<w:tcBorders {nsdecls("w")}>'
            f'<w:top w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'<w:left w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'<w:bottom w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'<w:right w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'</w:tcBorders>'
        )
        tcPr.append(borders)

    # Top Logo and Header
    logo_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "csrl_logo.png")
    if not os.path.exists(logo_path):
        logo_path = os.path.join(PROJECT_ROOT, "assets", "csrl_logo.png")

    if os.path.exists(logo_path):
        try:
            t_hdr = doc.add_table(rows=1, cols=2)
            t_hdr.autofit = False
            t_hdr.columns[0].width = Inches(0.85)
            t_hdr.columns[1].width = Inches(8.95)
            cell_logo = t_hdr.rows[0].cells[0]
            cell_text = t_hdr.rows[0].cells[1]
            p_l = cell_logo.paragraphs[0]
            p_l.add_run().add_picture(logo_path, width=Inches(0.75))
            
            p_t = cell_text.paragraphs[0]
            r1 = p_t.add_run("CYBER SECURITY RESEARCH LAB (CSRL)\n")
            r1.font.name = 'Calibri'
            r1.font.size = Pt(14)
            r1.font.bold = True
            r1.font.color.rgb = RGBColor(0x1E, 0x3A, 0x8A)
            
            r2 = p_t.add_run("REGULATORY COMPLIANCE AUDIT REPORT\n")
            r2.font.name = 'Calibri'
            r2.font.size = Pt(11)
            r2.font.bold = True
            r2.font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)
            
            r3 = p_t.add_run("Automated Multi-Agent Verification Benchmark")
            r3.font.name = 'Calibri'
            r3.font.size = Pt(9)
            r3.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)
            doc.add_paragraph() # spacer
        except Exception:
            p_title = doc.add_paragraph()
            r_t = p_title.add_run("CYBER SECURITY RESEARCH LAB (CSRL)\nCOMPLIANCE ASSESSMENT REPORT")
            r_t.font.name = 'Calibri'
            r_t.font.size = Pt(16)
            r_t.font.bold = True
            r_t.font.color.rgb = RGBColor(0x1E, 0x3A, 0x8A)
    else:
        p_title = doc.add_paragraph()
        r_t = p_title.add_run("CYBER SECURITY RESEARCH LAB (CSRL)\nCOMPLIANCE ASSESSMENT REPORT")
        r_t.font.name = 'Calibri'
        r_t.font.size = Pt(16)
        r_t.font.bold = True
        r_t.font.color.rgb = RGBColor(0x1E, 0x3A, 0x8A)

    detected_fw = resolve_canonical_framework_name(md_content, jurisdiction=jurisdiction, framework=framework)
    detected_client = extract_target_entity_name(md_content, fallback="Client_Application_v1.0")

    t_meta = doc.add_table(rows=4, cols=2)
    t_meta.style = 'Table Grid'
    meta_rows = [
        ("Client / Target Application", detected_client),
        ("Regulatory Standard / Framework", detected_fw),
        ("Audit Generation Timestamp (UTC)", datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")),
        ("Assessment Method", "Automated evidence assessment | Human review required"),
    ]
    for idx, (k, v) in enumerate(meta_rows):
        row = t_meta.rows[idx]
        row.cells[0].text = k
        row.cells[0].paragraphs[0].runs[0].font.bold = True
        row.cells[1].text = v
        set_cell_borders(row.cells[0])
        set_cell_borders(row.cells[1])
        if idx % 2 == 1:
            set_cell_shading(row.cells[0], "F8FAFC")
            set_cell_shading(row.cells[1], "F8FAFC")

    findings = extract_audit_findings_matrix(md_content, jurisdiction=jurisdiction, framework=framework)

    doc.add_heading("1. Executive Summary", level=2)
    exec_summary = build_comprehensive_executive_summary(md_content, detected_client, detected_fw, findings)
    for p_block in exec_summary.split("\n\n"):
        if p_block.strip():
            doc.add_paragraph(p_block.strip())

    doc.add_heading("2. Executive Compliance Scorecard", level=2)
    t_score = doc.add_table(rows=5, cols=3)
    t_score.style = 'Table Grid'
    score_headers = ["Compliance Status", "Count", "% of Assessable"]
    for i, h in enumerate(score_headers):
        cell = t_score.rows[0].cells[i]
        cell.text = h
        set_cell_shading(cell, "1E3A8A")
        cell.paragraphs[0].runs[0].font.bold = True
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    cnt_fully = sum(1 for f in findings if 'Fully' in f["status"])
    cnt_partial = sum(1 for f in findings if 'Partially' in f["status"])
    cnt_not = sum(1 for f in findings if 'Not' in f["status"])
    cnt_na = sum(1 for f in findings if any(k in f["status"].lower() for k in ['applicable', 'untested', 'pre-implementation', 'design']))
    assessable = cnt_fully + cnt_partial + cnt_not
    pct_f = f"{(cnt_fully/assessable*100):.1f}%" if assessable > 0 else "0.0%"
    pct_p = f"{(cnt_partial/assessable*100):.1f}%" if assessable > 0 else "0.0%"
    pct_n = f"{(cnt_not/assessable*100):.1f}%" if assessable > 0 else "0.0%"

    score_rows = [
        ("Fully Compliant", str(cnt_fully), pct_f),
        ("Partially Compliant", str(cnt_partial), pct_p),
        ("Not Compliant", str(cnt_not), pct_n),
        ("Evaluated Scope Items / Not Applicable", str(cnt_na), "—"),
    ]
    for idx, (lbl, cnt_str, pct_str) in enumerate(score_rows, start=1):
        row = t_score.rows[idx]
        row.cells[0].text = lbl
        row.cells[1].text = cnt_str
        row.cells[2].text = pct_str

    doc.add_heading("3. Technical Control Assessment Matrix", level=2)
    num_findings = len(findings) if findings else 1
    t_mat = doc.add_table(rows=num_findings + 1, cols=5)
    t_mat.style = 'Table Grid'
    mat_headers = ["Control ID", "Requirement Description", "Compliance Status", "Auditor Finding & Rationale", "Recommended Remediation"]
    for i, h in enumerate(mat_headers):
        cell = t_mat.rows[0].cells[i]
        cell.text = h
        set_cell_shading(cell, "1E3A8A")
        cell.paragraphs[0].runs[0].font.bold = True
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    if findings:
        for f_idx, finding in enumerate(findings, start=1):
            row = t_mat.rows[f_idx]
            row.cells[0].text = finding["control_id"]
            row.cells[1].text = finding["title"]
            row.cells[2].text = finding["status"]
            row.cells[3].text = finding["rationale"]
            row.cells[4].text = finding["remediation"]

    doc.add_heading("4. Remediation Action Plan & Engineering Milestones", level=2)
    
    action_items = [f for f in findings if f.get("status") in ("Not Compliant", "Partially Compliant", "Untested")]
    evidence_gap_items = [f for f in findings if f.get("status") == "No Evidence Found"]
    cat_auth = [f["control_id"] for f in action_items if any(k in f["title"].lower() or k in f["rationale"].lower() or k in f["remediation"].lower() for k in ["auth", "rbac", "admin", "token", "jwt", "password", "session", "access"])]
    cat_crypto = [f["control_id"] for f in action_items if f["control_id"] not in cat_auth and any(k in f["title"].lower() or k in f["rationale"].lower() or k in f["remediation"].lower() for k in ["encrypt", "aes", "cipher", "crypto", "tls", "https", "sanitiz", "validat"])]
    cat_logs = [f["control_id"] for f in action_items if f["control_id"] not in cat_auth and f["control_id"] not in cat_crypto and any(k in f["title"].lower() or k in f["rationale"].lower() or k in f["remediation"].lower() for k in ["log", "audit", "trail", "monitor", "event", "breach"])]
    cat_gov = [f["control_id"] for f in action_items if f["control_id"] not in cat_auth and f["control_id"] not in cat_crypto and f["control_id"] not in cat_logs]

    road_rows = []
    if cat_auth:
        road_rows.append(("Access Control & Identity Enforcement", ", ".join(cat_auth), "Enforce role-to-permission mapping and verified authentication tokens across all privileged operations."))
    if cat_crypto:
        road_rows.append(("Data Protection & Cryptography", ", ".join(cat_crypto), "Enforce robust data-at-rest encryption, verified TLS in transit, and centralized input sanitization."))
    if cat_logs:
        road_rows.append(("Security Logging & Audit Trails", ", ".join(cat_logs), "Implement persistent security event logging, tamper-evident audit trails, and timely incident detection."))
    if cat_gov:
        road_rows.append(("Governance & Procedural Verification", ", ".join(cat_gov), "Formalize operational procedures, data subject request (DSAR) workflows, and documented compliance policies."))
    if evidence_gap_items:
        road_rows.append(("Evidence Collection & Verification", ", ".join(f["control_id"] for f in evidence_gap_items), "Collect control-specific implementation evidence or authorized test results before making a compliance determination."))
    
    if not road_rows:
        road_rows.append(("Baseline Maintenance", "All Controls", "Maintain existing verified technical safeguards and continue periodic review cycles."))

    t_road = doc.add_table(rows=len(road_rows) + 1, cols=3)
    t_road.style = 'Table Grid'
    road_headers = ["Security Action Domain", "Target Controls Affected", "Engineering Milestone & Action"]
    for i, h in enumerate(road_headers):
        cell = t_road.rows[0].cells[i]
        cell.text = h
        set_cell_shading(cell, "1E3A8A")
        cell.paragraphs[0].runs[0].font.bold = True
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    for idx, (p, c, a) in enumerate(road_rows, start=1):
        row = t_road.rows[idx]
        row.cells[0].text = p
        row.cells[1].text = c
        row.cells[2].text = a

    doc.add_heading("5. Verification & Auditor Sign-Off", level=2)
    doc.add_paragraph("This compliance audit artifact was synthesized by the ComplianceMesh Multi-Agent Pipeline and verified against statutory ground-truth catalogs.")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


CanvasBase = canvas.Canvas if canvas is not None else object

class NumberedCanvas(CanvasBase):
    """
    Two-pass canvas to dynamically compute and draw total page count and professional headers/footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 8.5 * 72 - 25, "CYBER SECURITY RESEARCH LAB (CSRL)")
            self.drawRightString(11 * 72 - 36, 8.5 * 72 - 25, "Regulatory Compliance Audit Report | Confidential")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(36, 8.5 * 72 - 28, 11 * 72 - 36, 8.5 * 72 - 28)
            
        # Footer
        self.drawString(36, 20, "CSRL Cyber Security Research Lab | Multi-Agent Audit Engine | Confidential")
        self.drawRightString(11 * 72 - 36, 20, f"Page {self._pageNumber} of {page_count}")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 28, 11 * 72 - 36, 28)
        
        self.restoreState()


def render_pdf_report_bytes(md_content: str, jurisdiction: str = "nist", framework: str = "csf") -> bytes:
    """
    Renders a publication-grade Landscape PDF audit document using ReportLab:
    - Top Banner: Official CSRL Logo & Laboratory Header
    - Table 1: Client Metadata Card (2 columns)
    - Table 2: Executive Compliance Scorecard (3 columns, no emojis)
    - Table 3: 5-Column Technical Control Assessment Matrix (repeating header across pages)
    - Table 4: Domain-Based Engineering Remediation Action Plan
    """
    import io
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    # 1. Metadata Extraction
    detected_fw = resolve_canonical_framework_name(md_content, jurisdiction=jurisdiction, framework=framework)
    detected_client = extract_target_entity_name(md_content, fallback="Client_Application_v1.0")

    findings = extract_audit_findings_matrix(md_content, jurisdiction=jurisdiction, framework=framework)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=18,
        textColor=colors.HexColor('#1E3A8A'),
        spaceAfter=2
    )
    sub_style = ParagraphStyle(
        'ReportSub',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=12,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=8
    )
    h2_style = ParagraphStyle(
        'Heading2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11.5,
        leading=14,
        textColor=colors.HexColor('#1E3A8A'),
        spaceBefore=10,
        spaceAfter=5
    )
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor('#1E293B')
    )
    bold_style = ParagraphStyle(
        'BodyBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor('#1E293B')
    )
    th_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.white,
        alignment=0
    )
    
    status_styles = {
        'Fully Compliant': ParagraphStyle('StComp', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#166534')),
        'Partially Compliant': ParagraphStyle('StPart', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#854D0E')),
        'Not Compliant': ParagraphStyle('StNot', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#991B1B')),
        'Not Applicable': ParagraphStyle('StNA', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#475569')),
        'Untested': ParagraphStyle('StUnt', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#475569')),
    }

    elements = []

    # 1. Top Logo & Header Banner
    logo_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "csrl_logo.png")
    if not os.path.exists(logo_path):
        logo_path = os.path.join(PROJECT_ROOT, "assets", "csrl_logo.png")

    if os.path.exists(logo_path):
        try:
            logo_img = RLImage(logo_path, width=48, height=48)
            brand_text = (
                "<font size='13' color='#1E3A8A'><b>CYBER SECURITY RESEARCH LAB (CSRL)</b></font><br/>"
                "<font size='10' color='#1E293B'><b>REGULATORY COMPLIANCE AUDIT REPORT</b></font><br/>"
                f"<font size='8' color='#64748B'>Automated Multi-Agent Verification Benchmark &bull; {detected_fw.upper()}</font>"
            )
            brand_p = Paragraph(brand_text, title_style)
            t_header = Table([[logo_img, brand_p]], colWidths=[56, 664])
            t_header.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 0),
                ('TOPPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(t_header)
        except Exception:
            elements.append(Paragraph("CYBER SECURITY RESEARCH LAB (CSRL)", title_style))
            elements.append(Paragraph("REGULATORY COMPLIANCE AUDIT REPORT", sub_style))
    else:
        elements.append(Paragraph("CYBER SECURITY RESEARCH LAB (CSRL)", title_style))
        elements.append(Paragraph("REGULATORY COMPLIANCE AUDIT REPORT", sub_style))

    elements.append(Spacer(1, 4))

    # Table 1: Metadata Card (Width = 720 pt)
    meta_data = [
        [Paragraph("Client / Target Application", bold_style), Paragraph(detected_client, body_style)],
        [Paragraph("Regulatory Standard / Framework", bold_style), Paragraph(detected_fw, body_style)],
        [Paragraph("Audit Generation Timestamp (UTC)", bold_style), Paragraph(datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"), body_style)],
        [Paragraph("Assessment Method", bold_style), Paragraph("Automated evidence assessment | Human review required", body_style)],
    ]
    t_meta = Table(meta_data, colWidths=[200, 520])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#FFFFFF')),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_meta)
    elements.append(Spacer(1, 10))

    # Executive Summary Section
    elements.append(Paragraph("1. Executive Summary", h2_style))
    exec_summary = build_comprehensive_executive_summary(md_content, detected_client, detected_fw, findings)
    for p_block in exec_summary.split("\n\n"):
        if p_block.strip():
            elements.append(Paragraph(p_block.strip(), body_style))
            elements.append(Spacer(1, 4))
    elements.append(Spacer(1, 8))

    # Table 2: Executive Compliance Scorecard (No Emojis)
    elements.append(Paragraph("2. Executive Compliance Scorecard", h2_style))
    cnt_f = sum(1 for f in findings if 'Fully' in f['status'])
    cnt_p = sum(1 for f in findings if 'Partially' in f['status'])
    cnt_n = sum(1 for f in findings if 'Not' in f['status'])
    cnt_no_evidence = sum(1 for f in findings if "no evidence" in f["status"].lower())
    cnt_na = sum(1 for f in findings if any(k in f["status"].lower() for k in ["applicable", "untested", "pre-implementation", "design"]))
    tot_assess = cnt_f + cnt_p + cnt_n
    
    pct_f = f"{(cnt_f / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"
    pct_p = f"{(cnt_p / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"
    pct_n = f"{(cnt_n / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"

    score_data = [
        [Paragraph("Compliance Status", th_style), Paragraph("Count", th_style), Paragraph("% of Assessable", th_style)],
        [Paragraph("Fully Compliant", status_styles['Fully Compliant']), Paragraph(str(cnt_f), bold_style), Paragraph(pct_f, body_style)],
        [Paragraph("Partially Compliant", status_styles['Partially Compliant']), Paragraph(str(cnt_p), bold_style), Paragraph(pct_p, body_style)],
        [Paragraph("Not Compliant", status_styles['Not Compliant']), Paragraph(str(cnt_n), bold_style), Paragraph(pct_n, body_style)],
        [Paragraph("No Evidence Found", status_styles["Not Applicable"]), Paragraph(str(cnt_no_evidence), bold_style), Paragraph("Not a non-compliance verdict", body_style)],
        [Paragraph("Evaluated Scope Items / Not Applicable", status_styles['Not Applicable']), Paragraph(str(cnt_na), bold_style), Paragraph("—", body_style)],
    ]
    t_score = Table(score_data, colWidths=[260, 160, 300])
    t_score.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_score)
    elements.append(Spacer(1, 14))

    # Table 3: Technical Control Assessment Matrix (5 Columns, Width = 720 pt)
    elements.append(Paragraph("3. Technical Control Assessment Matrix", h2_style))
    matrix_headers = [
        Paragraph("Control ID", th_style),
        Paragraph("Requirement Description", th_style),
        Paragraph("Compliance Status", th_style),
        Paragraph("Auditor Finding & Rationale", th_style),
        Paragraph("Recommended Remediation", th_style)
    ]
    matrix_data = [matrix_headers]

    for f in findings:
        st_val = f['status']
        st_style = status_styles.get(st_val, body_style)
        matrix_data.append([
            Paragraph(f['control_id'], bold_style),
            Paragraph(f['title'], body_style),
            Paragraph(st_val, st_style),
            Paragraph(f['rationale'], body_style),
            Paragraph(f['remediation'], body_style)
        ])

    # Widths: 80 + 130 + 90 + 230 + 190 = 720 pt
    t_matrix = Table(matrix_data, colWidths=[80, 130, 90, 230, 190], repeatRows=1)
    t_matrix_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]
    for r_idx in range(1, len(matrix_data)):
        bg = colors.HexColor('#F8FAFC') if r_idx % 2 == 0 else colors.HexColor('#FFFFFF')
        t_matrix_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), bg))
    t_matrix.setStyle(TableStyle(t_matrix_style))
    elements.append(t_matrix)
    elements.append(Spacer(1, 14))

    # Table 4: Actionable Remediation Roadmap & Engineering Milestones (Width = 720 pt)
    elements.append(Paragraph("4. Remediation Action Plan & Engineering Milestones", h2_style))
    
    action_items = [f for f in findings if f.get("status") in ("Not Compliant", "Partially Compliant", "Untested")]
    evidence_gap_items = [f for f in findings if f.get("status") == "No Evidence Found"]
    cat_auth = [f["control_id"] for f in action_items if any(k in f["title"].lower() or k in f["rationale"].lower() or k in f["remediation"].lower() for k in ["auth", "rbac", "admin", "token", "jwt", "password", "session", "access"])]
    cat_crypto = [f["control_id"] for f in action_items if f["control_id"] not in cat_auth and any(k in f["title"].lower() or k in f["rationale"].lower() or k in f["remediation"].lower() for k in ["encrypt", "aes", "cipher", "crypto", "tls", "https", "sanitiz", "validat"])]
    cat_logs = [f["control_id"] for f in action_items if f["control_id"] not in cat_auth and f["control_id"] not in cat_crypto and any(k in f["title"].lower() or k in f["rationale"].lower() or k in f["remediation"].lower() for k in ["log", "audit", "trail", "monitor", "event", "breach"])]
    cat_gov = [f["control_id"] for f in action_items if f["control_id"] not in cat_auth and f["control_id"] not in cat_crypto and f["control_id"] not in cat_logs]

    road_rows = []
    if cat_auth:
        road_rows.append([Paragraph("Access Control & Identity Enforcement", bold_style), Paragraph(", ".join(cat_auth), body_style), Paragraph("Enforce role-to-permission mapping and verified authentication tokens across all privileged operations.", body_style)])
    if cat_crypto:
        road_rows.append([Paragraph("Data Protection & Cryptography", bold_style), Paragraph(", ".join(cat_crypto), body_style), Paragraph("Enforce robust data-at-rest encryption, verified TLS in transit, and centralized input sanitization.", body_style)])
    if cat_logs:
        road_rows.append([Paragraph("Security Logging & Audit Trails", bold_style), Paragraph(", ".join(cat_logs), body_style), Paragraph("Implement persistent security event logging, tamper-evident audit trails, and timely incident detection.", body_style)])
    if cat_gov:
        road_rows.append([Paragraph("Governance & Procedural Verification", bold_style), Paragraph(", ".join(cat_gov), body_style), Paragraph("Formalize operational procedures, data subject request (DSAR) workflows, and documented compliance policies.", body_style)])
    if evidence_gap_items:
        road_rows.append([Paragraph("Evidence Collection & Verification", bold_style), Paragraph(", ".join(f["control_id"] for f in evidence_gap_items), body_style), Paragraph("Collect control-specific implementation evidence or authorized test results before making a compliance determination.", body_style)])
    
    if not road_rows:
        road_rows.append([Paragraph("Baseline Maintenance", bold_style), Paragraph("All Controls", body_style), Paragraph("Maintain existing verified technical safeguards and continue periodic review cycles.", body_style)])

    road_data = [
        [Paragraph("Security Action Domain", th_style), Paragraph("Target Controls Affected", th_style), Paragraph("Engineering Milestone & Action", th_style)]
    ] + road_rows

    t_road = Table(road_data, colWidths=[180, 180, 360])
    t_road.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_road)
    elements.append(Spacer(1, 14))

    # 5. Verification Sign-Off
    elements.append(Paragraph("5. Verification & Auditor Sign-Off", h2_style))
    elements.append(Paragraph(
        "This automated assessment is limited to the submitted evidence and authorized probe results. "
        "Only explicit failed probes or directly observable insecure configurations support a Not Compliant finding. "
        "No Evidence Found and Untested entries are evidence gaps, not compliance verdicts, and require human review.",
        body_style
    ))

    doc.build(elements, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


def export_pdf(md_content: str, jurisdiction: str = "nist", framework: str = "csf", output_path: str = None) -> bytes:
    """
    Exports a Markdown report to a publication-grade PDF.
    """
    pdf_bytes = render_pdf_report_bytes(md_content, jurisdiction=jurisdiction, framework=framework)
    if output_path:
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
    return pdf_bytes


def extract_target_entity_name(md_content: str, fallback: str = "Client_App") -> str:
    """
    Extracts the clean repository name, zip file name, staging domain, or organization name from report content.
    e.g. 'https://github.com/fleetbase/fleetbase' -> 'fleetbase'
         'https://staging-api.fleetbase.io' -> 'fleetbase'
         'Client / Target Application fleetbaselive' -> 'fleetbaselive'
         'my_project.zip' -> 'my_project'
         'Acme Corp' -> 'Acme_Corp'
    """
    from urllib.parse import urlparse

    # 1. Search for explicit key-value pairs with colon (handling markdown bolding ** and #)
    patterns_colon = [
        r'(?:^|\n|\|)\s*(?:\*\*|#+)?\s*(?:Client\s*/\s*Target\s+Application|Target\s+Application|Target\s+Repository|Repository\s+Target|Target\s+URL|Staging\s+URL|Target\s+Endpoint|Target\s+Host|Client\s+ID|Org\s+Name|Organization|Company|Repository|Platform|System|Client|Host|URL|Repo)\s*(?:\*\*)?\s*:\s*(?:\*\*)?\s*`?([^|\n`*]+)',
        r'(?:^|\n|\|)\s*(?:\*\*|#+)?\s*(?:Zip\s+File|Uploaded\s+File|Source\s+Archive|Target\s+Archive|Source\s+Code\s+Archive|Archive|Source|Target)\s*(?:\*\*)?\s*:\s*(?:\*\*)?\s*`?([^|\n`*]+)',
    ]
    for pattern in patterns_colon:
        m = re.search(pattern, md_content, re.IGNORECASE)
        if m and m.group(1).strip():
            raw_val = m.group(1).strip().strip('*').strip('`').strip()
            if not raw_val.lower().startswith(('remediation', 'plan', 'assessment', 'id:', 'scan', 'details', 'baseline', 'standard', 'framework')):
                if "github.com" in raw_val or "gitlab.com" in raw_val or ("/" in raw_val and not raw_val.startswith("/")):
                    clean_val = raw_val.rstrip("/").split("/")[-1].replace(".git", "")
                    if clean_val and clean_val.lower() not in ("github.com", "gitlab.com"):
                        return re.sub(r'[^A-Za-z0-9_\-]', '_', clean_val)
                if "http" in raw_val:
                    parsed = urlparse(raw_val)
                    host = parsed.netloc or parsed.path
                    host_clean = host.split(":")[0]
                    if host_clean:
                        parts = host_clean.split(".")
                        domain_name = parts[-2] if len(parts) >= 2 and parts[-2] not in ("staging-api", "staging", "api", "app", "dev") else parts[0]
                        if domain_name in ("staging-api", "staging", "api", "app", "dev") and len(parts) >= 3:
                            domain_name = parts[-2]
                        return re.sub(r'[^A-Za-z0-9_\-]', '_', domain_name)
                if any(ext in raw_val.lower() for ext in ['.zip', '.tar.gz', '.tgz', '.tar']):
                    m_f = re.search(r'([A-Za-z0-9_\-]+)\.(?:zip|tar\.gz|tgz|tar)', raw_val, re.IGNORECASE)
                    if m_f:
                        return m_f.group(1)
                clean_val = re.sub(r'[^A-Za-z0-9_\- ]', '', raw_val).strip().replace(" ", "_")
                if clean_val and clean_val.lower() not in ["none", "n/a", "unknown"]:
                    return clean_val

    # 2. Search for plain text key-value pairs without colon (e.g. from pasted table text)
    patterns_plain = [
        r'(?:Client\s*/\s*Target\s+Application|Target\s+Application|Client\s+ID|Target\s+Repository)\s+([A-Za-z0-9_\-\.]+)',
    ]
    for pattern in patterns_plain:
        m = re.search(pattern, md_content, re.IGNORECASE)
        if m and m.group(1).strip():
            raw_val = m.group(1).strip()
            if raw_val.lower() not in ["regulatory", "standard", "framework", "none", "n/a"]:
                return re.sub(r'[^A-Za-z0-9_\-]', '_', raw_val)

    # 3. Search for any .zip filename in the header lines
    m_zip = re.search(r'([A-Za-z0-9_\-]+)\.(?:zip|tar\.gz|tgz|tar)', md_content[:2000], re.IGNORECASE)
    if m_zip:
        return m_zip.group(1)
        
    # 4. Search for any github repo in the header lines
    m_git = re.search(r'github\.com/[A-Za-z0-9_\-]+/([A-Za-z0-9_\-]+)', md_content[:2000], re.IGNORECASE)
    if m_git:
        return m_git.group(1)

    return fallback


def export_docx(md_content: str, jurisdiction: str = "nist", framework: str = "csf", output_path: str = None) -> bytes:
    """
    Exports a Markdown report to an executive Word (.docx) document.
    """
    docx_bytes = render_template_docx_bytes(md_content, jurisdiction=jurisdiction, framework=framework)
    if output_path:
        with open(output_path, "wb") as f:
            f.write(docx_bytes)
    return docx_bytes


def export_report(
    md_content: str,
    jurisdiction: str,
    framework: str,
    output_format: str,
    output_dir: str | None = None,
) -> str:
    """
    Exports a Markdown report to the specified format.

    Args:
        md_content: The Markdown report content.
        jurisdiction: e.g. "nist", "eu".
        framework: e.g. "csf", "gdpr".
        output_format: One of "html", "json", "txt", "docx", "pdf".
        output_dir: Output directory (defaults to REPORTS_DIR).

    Returns:
        Path to the exported file.
    """
    output_dir = output_dir or REPORTS_DIR
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    target_name = extract_target_entity_name(md_content, fallback=f"{jurisdiction}_{framework}")
    base_name = f"The_Audit_Report_of_{target_name}_{framework}_{timestamp}"

    if output_format == "pdf":
        out_path = os.path.join(output_dir, f"{base_name}.pdf")
        export_pdf(md_content, jurisdiction, framework, out_path)

    elif output_format == "docx":
        out_path = os.path.join(output_dir, f"{base_name}.docx")
        export_docx(md_content, jurisdiction, framework, out_path)

    elif output_format == "html":
        title = f"Compliance Report — {jurisdiction.upper()} / {framework.upper()}"
        body = markdown_to_html(md_content)
        content = HTML_TEMPLATE.format(
            title=html.escape(title),
            body=body,
            export_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
        out_path = os.path.join(output_dir, f"{base_name}.html")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

    elif output_format == "json":
        data = markdown_to_json(md_content, jurisdiction, framework)
        out_path = os.path.join(output_dir, f"{base_name}.json")
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    elif output_format == "txt":
        content = markdown_to_text(md_content)
        out_path = os.path.join(output_dir, f"{base_name}.txt")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

    elif output_format == "docx":
        out_path = os.path.join(output_dir, f"{base_name}.docx")
        export_docx(md_content, jurisdiction, framework, out_path)

    else:
        raise ValueError(f"Unsupported format: '{output_format}'. Use 'html', 'json', 'txt', or 'docx'.")

    # Log export
    try:
        import pipeline_logger
        pipeline_logger.log_info(
            "report_export",
            f"Exported {output_format.upper()} report: {out_path}",
            extra={"format": output_format, "path": out_path},
        )
    except ImportError:
        pass

    return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Multi-Format Report Exporter")
    parser.add_argument(
        "--framework", required=True,
        help="Jurisdiction/framework slug, e.g. 'nist/csf' or 'eu/gdpr'"
    )
    parser.add_argument(
        "--format", required=True, choices=["html", "json", "txt", "all"],
        help="Output format: html, json, txt, or all"
    )
    parser.add_argument(
        "--input", default=None,
        help="Path to a specific Markdown report file (auto-detected if omitted)"
    )
    args = parser.parse_args()

    jurisdiction, framework = args.framework.split("/")

    if args.input:
        md_path = args.input
    else:
        md_path = find_latest_report(jurisdiction, framework)
        if not md_path:
            print(f"No Markdown report found for {jurisdiction}/{framework} in '{REPORTS_DIR}/'.")
            print("Run Agent 5 first, or specify --input path.")
            return

    print(f"Source report: {md_path}")
    with open(md_path, encoding="utf-8-sig") as f:
        md_content = f.read()

    formats = ["html", "json", "txt"] if args.format == "all" else [args.format]

    for fmt in formats:
        out_path = export_report(md_content, jurisdiction, framework, fmt)
        print(f"  Exported {fmt.upper():>4} → {out_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
