"""
Report Exporter — Multi-Format Compliance Report Export
---------------------------------------------------------
Takes the Markdown report generated by Agent 5 (agent5_report_generation.py)
and exports it to additional formats: HTML, JSON, and plain text.

Usage:
    python report_exporter.py --framework nist/csf --format html
    python report_exporter.py --framework eu/gdpr --format json
    python report_exporter.py --framework india/dpdp --format txt

    # Export all formats at once
    python report_exporter.py --framework nist/csf --format all

This module does NOT modify agent5_report_generation.py — it reads existing
Markdown reports and converts them.
"""

import os
import re
import sys
import json
import glob
import argparse
from datetime import datetime

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
except ImportError:
    canvas = None
    colors = None

# Ensure project root is importable
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)


REPORTS_DIR = "reports"


# ---------------------------------------------------------------------------
# Markdown -> HTML
# ---------------------------------------------------------------------------
HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg: #0a0e1a;
            --surface: #111827;
            --border: #1e293b;
            --text: #e2e8f0;
            --accent: #818cf8;
            --success: #34d399;
            --warning: #fbbf24;
            --danger: #f87171;
            --muted: #94a3b8;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', 'Inter', system-ui, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.7;
            padding: 2rem;
            max-width: 1000px;
            margin: 0 auto;
        }}
        h1 {{
            color: var(--accent);
            font-size: 2rem;
            margin-bottom: 1rem;
            border-bottom: 2px solid var(--border);
            padding-bottom: 0.5rem;
        }}
        h2 {{
            color: var(--accent);
            font-size: 1.4rem;
            margin-top: 2rem;
            margin-bottom: 0.8rem;
        }}
        h3 {{
            color: var(--text);
            font-size: 1.1rem;
            margin-top: 1.5rem;
            margin-bottom: 0.5rem;
        }}
        p, li {{
            margin-bottom: 0.5rem;
        }}
        strong {{
            color: #f1f5f9;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            background: var(--surface);
            border-radius: 8px;
            overflow: hidden;
        }}
        th, td {{
            padding: 0.75rem 1rem;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }}
        th {{
            background: rgba(129, 140, 248, 0.1);
            color: var(--accent);
            font-weight: 600;
        }}
        hr {{
            border: none;
            border-top: 1px solid var(--border);
            margin: 1.5rem 0;
        }}
        code {{
            background: var(--surface);
            padding: 0.15rem 0.4rem;
            border-radius: 4px;
            font-size: 0.9em;
        }}
        ul {{
            padding-left: 1.5rem;
        }}
        .footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border);
            color: var(--muted);
            font-size: 0.85rem;
            font-style: italic;
        }}
    </style>
</head>
<body>
{body}
<div class="footer">
    Exported on {export_date} by ComplianceMesh Report Exporter
</div>
</body>
</html>
"""


def markdown_to_html(md_content: str) -> str:
    """
    Converts Markdown to HTML using simple regex-based transformation.
    Handles: headings, bold, tables, horizontal rules, lists, code, and paragraphs.
    """
    lines = md_content.split("\n")
    html_lines = []
    in_table = False
    in_list = False

    for line in lines:
        stripped = line.strip()

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            if in_table:
                html_lines.append("</table>")
                in_table = False
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<hr>")
            continue

        # Table separator row (|---|---|)
        if re.match(r"^\|[-:|]+\|$", stripped):
            continue

        # Table row
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.split("|")[1:-1]]
            if not in_table:
                html_lines.append("<table>")
                in_table = True
                # First row is header
                html_lines.append("<tr>" + "".join(f"<th>{_inline_md(c)}</th>" for c in cells) + "</tr>")
            else:
                html_lines.append("<tr>" + "".join(f"<td>{_inline_md(c)}</td>" for c in cells) + "</tr>")
            continue

        if in_table and not stripped.startswith("|"):
            html_lines.append("</table>")
            in_table = False

        # Headings
        if stripped.startswith("### "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h3>{_inline_md(stripped[4:])}</h3>")
            continue
        if stripped.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h2>{_inline_md(stripped[3:])}</h2>")
            continue
        if stripped.startswith("# "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h1>{_inline_md(stripped[2:])}</h1>")
            continue

        # List items
        if stripped.startswith("- "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{_inline_md(stripped[2:])}</li>")
            continue

        if in_list and stripped and not stripped.startswith("- "):
            html_lines.append("</ul>")
            in_list = False

        # Paragraph
        if stripped:
            html_lines.append(f"<p>{_inline_md(stripped)}</p>")

    if in_table:
        html_lines.append("</table>")
    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Converts inline Markdown (bold, code, links) to HTML."""
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Inline code
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    return text


# ---------------------------------------------------------------------------
# Markdown -> JSON
# ---------------------------------------------------------------------------
def markdown_to_json(md_content: str, jurisdiction: str, framework: str) -> dict:
    """
    Parses the Markdown report into a structured JSON representation.
    """
    sections = re.split(r"\n## ", md_content)

    result = {
        "jurisdiction": jurisdiction,
        "framework": framework,
        "export_format": "json",
        "exported_at": datetime.now().isoformat(),
        "sections": {},
    }

    for section in sections:
        lines = section.strip().split("\n")
        if not lines:
            continue
        title = lines[0].strip().lstrip("# ").strip()
        content = "\n".join(lines[1:]).strip()
        result["sections"][title] = content

    return result


# ---------------------------------------------------------------------------
# Markdown -> Plain Text
# ---------------------------------------------------------------------------
def markdown_to_text(md_content: str) -> str:
    """Strips Markdown formatting for plain-text email-friendly output."""
    text = md_content
    # Remove heading markers
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Remove bold markers
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    # Remove inline code markers
    text = re.sub(r"`(.+?)`", r"\1", text)
    # Remove table formatting (keep content)
    text = re.sub(r"^\|[-:|]+\|$", "", text, flags=re.MULTILINE)
    text = re.sub(r"\|", "  ", text)
    # Remove horizontal rules
    text = re.sub(r"^---+$", "-" * 60, text, flags=re.MULTILINE)
    return text.strip()


# ---------------------------------------------------------------------------
# Export orchestration
# ---------------------------------------------------------------------------
def find_latest_report(jurisdiction: str, framework: str) -> str | None:
    """Finds the most recent Markdown report for the given jurisdiction/framework."""
    pattern = os.path.join(REPORTS_DIR, f"{jurisdiction}__{framework}_report_*.md")
    reports = sorted(glob.glob(pattern))
    if reports:
        return reports[-1]  # most recent by timestamp in filename
    return None


def strip_all_markdown_and_emojis(text: str) -> str:
    """
    Strips all emojis, decorative symbols, and markdown markup
    (e.g., **, *, `, #, list markers, [link](url)) from text.
    """
    if not text:
        return ""
    emoji_pattern = re.compile(
        r'[\U00010000-\U0010ffff]|[\u2600-\u27bf]|[\u2300-\u23ff]|[\u2b50-\u2b55]|[\u200d\ufe0f\u20e3]|'
        r'[✅⚠️❌⛔🔹🔸▪️•💻⚪🐙🔍📊📘📄📑📕]',
        flags=re.UNICODE
    )
    cleaned = emoji_pattern.sub('', text)
    cleaned = re.sub(r'\*{1,3}', '', cleaned)
    cleaned = re.sub(r'_{1,3}', '', cleaned)
    cleaned = re.sub(r'`+', '', cleaned)
    cleaned = re.sub(r'#{1,6}\s*', '', cleaned)
    cleaned = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', cleaned)
    cleaned = re.sub(r'^\s*[-*•]\s*', '', cleaned)
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()
    return cleaned


def extract_canonical_control_id(raw_text: str) -> str:
    """
    STRICT CONTROL ID EXTRACTOR:
    Extracts ONLY the formal statutory or technical control identifier
    (e.g., Recital 91, Article 32, 34.3.a, 6.3.257, PR.AC-1, ID.GV-1, A.8.1, REQ-01, CWE-89).
    """
    cleaned = strip_all_markdown_and_emojis(raw_text)
    
    if '—' in cleaned:
        cleaned = cleaned.split('—')[0].strip()
    elif '–' in cleaned:
        cleaned = cleaned.split('–')[0].strip()
    elif ':' in cleaned and not cleaned.lower().startswith('http'):
        cleaned = cleaned.split(':')[0].strip()
        
    cleaned = cleaned.strip(' \t')
    
    patterns = [
        r'\b(NIST\s+SP\s+800-\d+\s+[A-Z]{2}-\d+)\b',
        r'\b([A-Z]{2,4}\.[A-Z]{2,4}-\d+(?:\.\d+)?)\b',
        r'\b(Recital\s+\d+)\b',
        r'\b(Article\s+\d+(?:\.\d+)?(?:\([a-z0-9]+\))?)\b',
        r'\b(Art\.?\s*\d+(?:\.\d+)?(?:\([a-z0-9]+\))?)\b',
        r'\b([A-Z]\.\d+\.\d+(?:\.\d+)?)\b',
        r'\b(REQ-\d+)\b',
        r'\b(CWE-\d+)\b',
        r'\b(ASVS-\d+\.\d+(?:\.\d+)?)\b',
        r'\b(\d+\.\d+(?:\.[a-z0-9]+)?(?:\.[a-z0-9]+)?)\b',
        r'\b(GAP-\d+)\b',
        r'\b([A-Z]{2,4}-\d+)\b'
    ]
    for p in patterns:
        m = re.search(p, cleaned, re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return cleaned[:25]


def extract_audit_findings_matrix(md_content: str, jurisdiction: str = "nist", framework: str = "csf") -> list[dict]:
    """
    Extracts structured findings into a canonical list of 6-field dictionaries:
    [control_id, title, status, rationale, remediation, priority]
    Handles section-grouped findings, runtime probes, markdown tables, and headings.
    """
    raw_lines = md_content.split('\n')
    norm_lines = []
    current_t_row = ""
    for r_line in raw_lines:
        s_line = r_line.strip()
        if not s_line:
            if current_t_row:
                norm_lines.append(current_t_row)
                current_t_row = ""
            continue
        if s_line.startswith('|'):
            if current_t_row:
                if current_t_row.count('|') >= 3 and current_t_row.endswith('|'):
                    norm_lines.append(current_t_row)
                    current_t_row = s_line
                else:
                    current_t_row += " " + s_line
            else:
                current_t_row = s_line
        elif current_t_row:
            current_t_row += " " + s_line
        else:
            norm_lines.append(s_line)
    if current_t_row:
        norm_lines.append(current_t_row)

    findings = []

    # Strategy 1: Section-grouped Headings
    current_section_status = None
    current_section_priority = None

    lines = md_content.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        clean_line = line.lstrip('#').strip().lower()
        
        is_section_header = (
            (line.startswith('#') or clean_line.startswith(('✅', '⚠️', '❌', '⛔')))
            and not clean_line.startswith(('*', '-', '•', '`', '🔹', '🔸'))
            and any(k in clean_line for k in ['control', 'matrix', 'finding', 'gap', 'scope'])
        )
        
        if is_section_header:
            if any(w in clean_line for w in ['not compliant', 'non-compliant', 'gaps / not compliant', 'gaps']):
                current_section_status = 'Not Compliant'
                current_section_priority = 'High (P0)'
            elif any(w in clean_line for w in ['partially compliant', 'partial']):
                current_section_status = 'Partially Compliant'
                current_section_priority = 'Medium (P1)'
            elif any(w in clean_line for w in ['fully compliant', 'compliant']) and not any(w in clean_line for w in ['not', 'non', 'gap']):
                current_section_status = 'Fully Compliant'
                current_section_priority = 'Closed'
            elif any(w in clean_line for w in ['evaluated scope', 'not applicable', 'pre-implementation']):
                current_section_status = 'Not Applicable'
                current_section_priority = 'Low (P2)'

        if line.startswith('🔹') or (line.startswith('#### ') and ('🔹' in line or '—' in line or '–' in line)) or ((line.startswith('### ') or line.startswith('- **')) and current_section_status is not None and ('—' in line or '–' in line)):
            raw_heading = re.sub(r'^#{3,4}\s*', '', line).strip()
            if not any(k in raw_heading.lower() for k in ['credential & secret', 'dependency & cve', 'dynamic control inspection', 'compliance breakdown', 'summary', 'static security']):
                cid = extract_canonical_control_id(raw_heading)
                
                title_part = ''
                if '—' in raw_heading:
                    title_part = raw_heading.split('—', 1)[1].strip()
                elif '–' in raw_heading:
                    title_part = raw_heading.split('–', 1)[1].strip()
                elif '-' in raw_heading:
                    title_part = raw_heading.split('-', 1)[1].strip()
                else:
                    title_part = raw_heading
                clean_title = strip_all_markdown_and_emojis(title_part)

                body_lines = []
                j = i + 1
                while j < len(lines):
                    nxt = lines[j].strip()
                    if nxt.startswith('🔹') or nxt.startswith('#### ') or (nxt.startswith('### ') and not nxt.startswith('####')) or nxt.startswith('---') or any(w in nxt.lower() for w in ['fully compliant controls', 'partially compliant controls', 'not compliant controls', 'gaps / not compliant']):
                        break
                    body_lines.append(nxt)
                    j += 1
                body_text = '\n'.join(body_lines)

                m_audit = re.findall(r'(?:\*\*Audit Finding:\*\*|Audit Finding:|\*\*Auditor Explanation:\*\*|Auditor Explanation:|\*\*Technical Restrictions:\*\*|Technical Restrictions:|\*\*Control Requirement:\*\*|Control Requirement:)\s*([^\n]+)', body_text)
                if m_audit:
                    cleaned_chunks = [strip_all_markdown_and_emojis(chunk) for chunk in m_audit if strip_all_markdown_and_emojis(chunk)]
                    rationale = ' '.join(cleaned_chunks)
                else:
                    m_rat = re.search(r'-\s*\*\*(?:Rationale|Auditor Explanation|Details):\*\*\s*([^\n]+)', body_text, re.IGNORECASE)
                    rationale = strip_all_markdown_and_emojis(m_rat.group(1)) if m_rat else f'Evaluated safeguard requirement for {clean_title}.'

                m_rem = re.search(r'(?:\*\*Client Remediation Plan:\*\*|Client Remediation Plan:)\s*([\s\S]+?)(?=(?:\n\s*[-*]\s*\*\*Evidence Source:\*\*|\n\s*[-*]\s*\*\*|\n\s*####|\n\s*🔹|\n\s*###|\Z))', body_text, re.IGNORECASE)
                if m_rem:
                    remediation = strip_all_markdown_and_emojis(m_rem.group(1))
                else:
                    m_rem2 = re.search(r'(?:\*\*Recommended Remediation:\*\*|Recommended Remediation:|\*\*Remediation:\*\*|Remediation:)\s*([^\n]+)', body_text, re.IGNORECASE)
                    if m_rem2:
                        remediation = strip_all_markdown_and_emojis(m_rem2.group(1))
                    else:
                        remediation = 'Maintain verified baseline.' if current_section_status == 'Fully Compliant' else 'Implement required safeguards to achieve compliance.'

                findings.append({
                    'control_id': cid,
                    'title': clean_title,
                    'status': current_section_status or 'Compliant',
                    'rationale': rationale[:450],
                    'remediation': remediation[:450],
                    'priority': current_section_priority or 'Closed'
                })

        if line.startswith('- **') and ('—' in line or '–' in line) and ':' in line:
            m_probe = re.match(r'-\s*\*\*([A-Za-z0-9_\.\-]+)\s*[—–-]\s*([^\*]+)\*\*:\s*([^\n]+)', line)
            if m_probe:
                p_cid = extract_canonical_control_id(m_probe.group(1))
                p_title = strip_all_markdown_and_emojis(m_probe.group(2))
                p_status_raw = m_probe.group(3).strip()

                status_val = 'Not Compliant' if 'fail' in p_status_raw.lower() else ('Untested' if 'no_data' in p_status_raw.lower() else 'Compliant')
                prio_val = 'High (P0)' if status_val == 'Not Compliant' else ('Low (P2)' if status_val == 'Untested' else 'Closed')

                findings.append({
                    'control_id': p_cid,
                    'title': p_title,
                    'status': status_val,
                    'rationale': f'Runtime probe status: {strip_all_markdown_and_emojis(p_status_raw)}',
                    'remediation': 'Address dynamic probe finding.' if prio_val != 'Closed' else 'Probe passed.',
                    'priority': prio_val
                })

        i += 1

    # Strategy 2: Table-based Findings Matrix
    if not findings:
        table_lines = [l.strip() for l in norm_lines if l.strip().startswith('|') and l.strip().endswith('|')]
        if len(table_lines) > 2:
            rows = [t for t in table_lines if not re.match(r'^\|[-:| ]+\|$', t)]
            if len(rows) > 1:
                header_cells = [c.strip().lower() for c in rows[0].split('|')[1:-1]]
                id_idx = next((idx_h for idx_h, h in enumerate(header_cells) if any(k in h for k in ['id', 'req', 'control'])), 0)
                title_idx = next((idx_h for idx_h, h in enumerate(header_cells) if any(k in h for k in ['design', 'title', 'requirement', 'description', 'name'])), 1 if len(header_cells) > 1 else 0)
                status_idx = next((idx_h for idx_h, h in enumerate(header_cells) if 'status' in h), -1)
                rem_idx = next((idx_h for idx_h, h in enumerate(header_cells) if any(k in h for k in ['remediation', 'action', 'recommendation'])), -1)

                for row in rows[1:]:
                    cells = [c.strip() for c in row.split('|')[1:-1]]
                    if len(cells) < 2:
                        continue
                    first_cell_clean = re.sub(r'[^\w\s]', '', cells[0]).strip().lower()
                    if any(first_cell_clean.startswith(w) for w in ['compliant', 'fully compliant', 'partially', 'not compliant', 'non compliant', 'not applicable', 'no evidence', 'total', 'control status', 'status', 'summary']):
                        continue

                    raw_id = cells[id_idx].strip() if id_idx < len(cells) else f"CTRL-{len(findings)+1}"
                    clean_id = extract_canonical_control_id(raw_id)
                    raw_title = strip_all_markdown_and_emojis(cells[title_idx]) if title_idx < len(cells) else "Security Requirement"
                    clean_title = re.sub(rf'^{re.escape(clean_id)}\s*[—–-]?\s*', '', raw_title, flags=re.IGNORECASE).strip() or raw_title
                    status_text = strip_all_markdown_and_emojis(cells[status_idx]) if (status_idx != -1 and status_idx < len(cells)) else "Evaluated"

                    st_low = status_text.lower()
                    if any(w in st_low for w in ['not compliant', 'fail', 'gap']):
                        priority = "High (P0)"
                    elif any(w in st_low for w in ['partially', 'partial']):
                        priority = "Medium (P1)"
                    elif any(w in st_low for w in ['not applicable', 'pre-implementation', 'design only']):
                        priority = "Low (P2)"
                    else:
                        priority = "Closed"

                    rem_text = strip_all_markdown_and_emojis(cells[rem_idx]) if (rem_idx != -1 and rem_idx < len(cells)) else ("Implement missing safeguard controls to achieve full compliance." if priority != "Closed" else "Maintain verified operational baseline.")

                    findings.append({
                        "control_id": clean_id,
                        "title": clean_title,
                        "status": status_text,
                        "rationale": f"Evaluated compliance baseline for {clean_title}.",
                        "remediation": rem_text,
                        "priority": priority
                    })

    # Strategy 3: Standard ### Headings
    if not findings:
        finding_blocks = re.findall(r'#{2,4}\s*([A-Za-z0-9_\.\-]+(?:\s*—\s*[^\n]+)?)\s*\n([\s\S]+?)(?=\n#{2,4}|\n---|\Z)', md_content)
        for title_line, body in finding_blocks:
            if any(w in title_line.lower() for w in ['executive summary', 'summary of findings', 'recommendation', 'auditor sign-off', 'actionable', 'control mapping', 'summary']):
                continue
            raw_id = title_line.split('—')[0].strip() if '—' in title_line else title_line.strip()
            clean_id = extract_canonical_control_id(raw_id)
            raw_title = strip_all_markdown_and_emojis(title_line.split('—')[1].strip() if '—' in title_line else "Control Safeguard")

            status = "Compliant"
            m_st = re.search(r'-\s*\*\*Status\*\*:\s*([^\n]+)', body, re.IGNORECASE)
            if m_st:
                status = strip_all_markdown_and_emojis(m_st.group(1))

            rationale = "Safeguard controls evaluated against standard baseline."
            m_exp = re.search(r'-\s*\*\*(?:Rationale|Auditor Explanation|Details|Explanation)\*\*:\s*([^\n]+)', body, re.IGNORECASE)
            if m_exp:
                rationale = strip_all_markdown_and_emojis(m_exp.group(1))

            remediation = "Maintain verified baseline." if "Compliant" in status and "Not" not in status else "Implement required safeguards."
            m_rem = re.search(r'-\s*\*\*(?:Recommended remediation|Remediation|Recommendation)\*\*:\s*([^\n]+)', body, re.IGNORECASE)
            if m_rem:
                remediation = strip_all_markdown_and_emojis(m_rem.group(1))

            st_low = status.lower()
            if any(w in st_low for w in ['not compliant', 'fail']):
                priority = "High (P0)"
            elif any(w in st_low for w in ['partially', 'partial']):
                priority = "Medium (P1)"
            elif any(w in st_low for w in ['not applicable', 'untested']):
                priority = "Low (P2)"
            else:
                priority = "Closed"

            findings.append({
                "control_id": clean_id,
                "title": raw_title,
                "status": status,
                "rationale": rationale,
                "remediation": remediation,
                "priority": priority
            })

    return findings


def render_template_docx_bytes(md_content: str, jurisdiction: str = "nist", framework: str = "csf") -> bytes:
    """
    Renders a professional 6-column Word (.docx) audit document:
    - Table 1: Client Metadata Card (2 columns)
    - Table 2: Executive Compliance Scorecard (3 columns, no emojis)
    - Table 3: 6-Column Technical Control Assessment Matrix
    - Table 4: Actionable Remediation Roadmap (3 columns)
    """
    import io
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml import parse_xml
    from docx.oxml.ns import nsdecls

    doc = docx.Document()

    # Landscape layout
    for section in doc.sections:
        section.top_margin = Inches(0.6)
        section.bottom_margin = Inches(0.6)
        section.left_margin = Inches(0.6)
        section.right_margin = Inches(0.6)
        section.orientation = docx.enum.section.WD_ORIENT.LANDSCAPE
        section.page_width = Inches(11.0)
        section.page_height = Inches(8.5)

    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(9.5)
    font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)

    def set_cell_shading(cell, color_hex):
        shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>')
        cell._tc.get_or_add_tcPr().append(shd)

    def set_cell_borders(cell, color_hex="CBD5E1"):
        tcPr = cell._tc.get_or_add_tcPr()
        borders = parse_xml(
            f'<w:tcBorders {nsdecls("w")}>'
            f'<w:top w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'<w:left w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'<w:bottom w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'<w:right w:val="single" w:sz="4" w:space="0" w:color="{color_hex}"/>'
            f'</w:tcBorders>'
        )
        tcPr.append(borders)

    p_title = doc.add_paragraph()
    r_t = p_title.add_run("COMPLIANCE ASSESSMENT REPORT")
    r_t.font.name = 'Calibri'
    r_t.font.size = Pt(18)
    r_t.font.bold = True
    r_t.font.color.rgb = RGBColor(0x1E, 0x3A, 0x8A)

    p_sub = doc.add_paragraph()
    r_sub = p_sub.add_run("Standardized Regulatory & Technical Audit Report")
    r_sub.font.name = 'Calibri'
    r_sub.font.size = Pt(10)
    r_sub.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)

    detected_fw = None
    for p_fw in [
        r'(?:Target Framework Benchmark|Framework Benchmark|Target Framework)[:\s*]+`?([^|\n`]+)',
        r'(?:Framework|Standard)[:\s*]+`?([^|\n`]+)'
    ]:
        m_f = re.search(p_fw, md_content, re.IGNORECASE)
        if m_f and m_f.group(1).strip() and not m_f.group(1).strip().lower().startswith(('status', 'matrix', 'summary', 'audit')):
            detected_fw = strip_all_markdown_and_emojis(m_f.group(1))
            break
    if not detected_fw:
        detected_fw = f"{jurisdiction.upper()}/{framework.upper()}"

    detected_client = None
    for p_cl in [
        r'(?:Repository Target|Target Repository)[:\s*]+`?([^|\n`]+)',
        r'(?:Client ID|Platform|Target Application|System)[:\s*]+`?([^|\n`]+)',
        r'Client[:\s*]+`?([^|\n`]+)'
    ]:
        m_c = re.search(p_cl, md_content, re.IGNORECASE)
        if m_c and m_c.group(1).strip() and not m_c.group(1).strip().lower().startswith(('remediation', 'plan', 'assessment', 'id:')):
            detected_client = strip_all_markdown_and_emojis(m_c.group(1))
            break
    if not detected_client:
        detected_client = "Client_Application_v1.0"

    t_meta = doc.add_table(rows=4, cols=2)
    t_meta.style = 'Table Grid'
    meta_rows = [
        ("Client / Target Application", detected_client),
        ("Regulatory Standard / Framework", detected_fw),
        ("Audit Generation Timestamp (UTC)", datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")),
        ("Assessor & Verification", "ComplianceMesh Multi-Agent Pipeline | Verified (Nemotron 3 Ultra)"),
    ]
    for idx, (k, v) in enumerate(meta_rows):
        row = t_meta.rows[idx]
        row.cells[0].text = k
        row.cells[0].paragraphs[0].runs[0].font.bold = True
        row.cells[1].text = v
        set_cell_borders(row.cells[0])
        set_cell_borders(row.cells[1])
        if idx % 2 == 1:
            set_cell_shading(row.cells[0], "F8FAFC")
            set_cell_shading(row.cells[1], "F8FAFC")

    doc.add_heading("1. Executive Summary", level=2)
    m_exec = re.search(r'(?:#{1,4}\s*Executive Summary|\*\*Executive Summary\*\*)\s*\n+([\s\S]+?)(?:\n#{1,4}|\n---|\Z)', md_content, re.IGNORECASE)
    exec_summary = m_exec.group(1).strip() if m_exec else f"Automated compliance assessment completed against {detected_fw} baseline."
    clean_exec = strip_all_markdown_and_emojis(exec_summary)
    doc.add_paragraph(clean_exec)

    findings = extract_audit_findings_matrix(md_content, jurisdiction=jurisdiction, framework=framework)

    doc.add_heading("2. Executive Compliance Scorecard", level=2)
    t_score = doc.add_table(rows=5, cols=3)
    t_score.style = 'Table Grid'
    score_headers = ["Compliance Status", "Count", "% of Assessable"]
    for i, h in enumerate(score_headers):
        cell = t_score.rows[0].cells[i]
        cell.text = h
        set_cell_shading(cell, "1E3A8A")
        cell.paragraphs[0].runs[0].font.bold = True
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    cnt_fully = sum(1 for f in findings if 'Fully' in f["status"])
    cnt_partial = sum(1 for f in findings if 'Partially' in f["status"])
    cnt_not = sum(1 for f in findings if 'Not' in f["status"])
    cnt_na = sum(1 for f in findings if any(k in f["status"].lower() for k in ['applicable', 'untested', 'pre-implementation', 'design']))
    assessable = cnt_fully + cnt_partial + cnt_not
    pct_f = f"{(cnt_fully/assessable*100):.1f}%" if assessable > 0 else "0.0%"
    pct_p = f"{(cnt_partial/assessable*100):.1f}%" if assessable > 0 else "0.0%"
    pct_n = f"{(cnt_not/assessable*100):.1f}%" if assessable > 0 else "0.0%"

    score_rows = [
        ("Fully Compliant", str(cnt_fully), pct_f),
        ("Partially Compliant", str(cnt_partial), pct_p),
        ("Not Compliant", str(cnt_not), pct_n),
        ("Evaluated Scope Items / Not Applicable", str(cnt_na), "—"),
    ]
    for idx, (lbl, cnt_str, pct_str) in enumerate(score_rows, start=1):
        row = t_score.rows[idx]
        row.cells[0].text = lbl
        row.cells[1].text = cnt_str
        row.cells[2].text = pct_str

    doc.add_heading("3. Technical Control Assessment Matrix", level=2)
    num_findings = len(findings) if findings else 1
    t_mat = doc.add_table(rows=num_findings + 1, cols=6)
    t_mat.style = 'Table Grid'
    mat_headers = ["Control ID", "Requirement Description", "Compliance Status", "Auditor Finding & Rationale", "Recommended Remediation", "Priority"]
    for i, h in enumerate(mat_headers):
        cell = t_mat.rows[0].cells[i]
        cell.text = h
        set_cell_shading(cell, "1E3A8A")
        cell.paragraphs[0].runs[0].font.bold = True
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    if findings:
        for f_idx, finding in enumerate(findings, start=1):
            row = t_mat.rows[f_idx]
            row.cells[0].text = finding["control_id"]
            row.cells[1].text = finding["title"]
            row.cells[2].text = finding["status"]
            row.cells[3].text = finding["rationale"]
            row.cells[4].text = finding["remediation"]
            row.cells[5].text = finding["priority"]

    doc.add_heading("4. Actionable Remediation Roadmap", level=2)
    t_road = doc.add_table(rows=4, cols=3)
    t_road.style = 'Table Grid'
    road_headers = ["Priority Tier", "Target Controls Affected", "Engineering Milestone & Action"]
    for i, h in enumerate(road_headers):
        cell = t_road.rows[0].cells[i]
        cell.text = h
        set_cell_shading(cell, "1E3A8A")
        cell.paragraphs[0].runs[0].font.bold = True
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    p0 = [f["control_id"] for f in findings if "P0" in f["priority"] or "Not Compliant" in f["status"]]
    p1 = [f["control_id"] for f in findings if "P1" in f["priority"] or "Partially Compliant" in f["status"]]
    p2 = [f["control_id"] for f in findings if "P2" in f["priority"] or "Not Applicable" in f["status"]]

    road_rows = [
        ("P0 (Immediate / 0–14 Days)", ", ".join(p0), "Remediate critical security gaps."),
        ("P1 (Near-Term / 30 Days)", ", ".join(p1), "Implement multi-factor authentication and logging."),
        ("P2 (Long-Term / 60 Days)", ", ".join(p2), "Formalize governance policies and review cycles."),
    ]
    for idx, (p, c, a) in enumerate(road_rows, start=1):
        row = t_road.rows[idx]
        row.cells[0].text = p
        row.cells[1].text = c
        row.cells[2].text = a

    doc.add_heading("5. Verification & Auditor Sign-Off", level=2)
    doc.add_paragraph("This compliance audit artifact was synthesized by the ComplianceMesh Multi-Agent Pipeline and verified against statutory ground-truth catalogs.")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw total page count and professional headers/footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawRightString(11 * 72 - 36, 8.5 * 72 - 25, "ComplianceMesh Regulatory Audit Report | Confidential")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(36, 8.5 * 72 - 28, 11 * 72 - 36, 8.5 * 72 - 28)
            
        # Footer
        self.drawString(36, 20, "Generated by ComplianceMesh Multi-Agent Audit Pipeline | Confidential")
        self.drawRightString(11 * 72 - 36, 20, f"Page {self._pageNumber} of {page_count}")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 28, 11 * 72 - 36, 28)
        
        self.restoreState()


def render_pdf_report_bytes(md_content: str, jurisdiction: str = "nist", framework: str = "csf") -> bytes:
    """
    Renders a publication-grade Landscape PDF audit document using ReportLab:
    - Table 1: Client Metadata Card (2 columns)
    - Table 2: Executive Compliance Scorecard (3 columns, no emojis)
    - Table 3: 6-Column Technical Control Assessment Matrix (Evidence column removed, repeating header across pages)
    - Table 4: Actionable Remediation Roadmap (3 columns)
    """
    import io
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    # 1. Metadata Extraction
    detected_fw = None
    for p_fw in [
        r'(?:Target Framework Benchmark|Framework Benchmark|Target Framework)[:\s*]+`?([^|\n`]+)',
        r'(?:Framework|Standard)[:\s*]+`?([^|\n`]+)'
    ]:
        m_f = re.search(p_fw, md_content, re.IGNORECASE)
        if m_f and m_f.group(1).strip() and not m_f.group(1).strip().lower().startswith(('status', 'matrix', 'summary', 'audit')):
            detected_fw = strip_all_markdown_and_emojis(m_f.group(1))
            break
    if not detected_fw:
        detected_fw = f"{jurisdiction.upper()}/{framework.upper()}"

    detected_client = None
    for p_cl in [
        r'(?:Repository Target|Target Repository)[:\s*]+`?([^|\n`]+)',
        r'(?:Client ID|Platform|Target Application|System)[:\s*]+`?([^|\n`]+)',
        r'Client[:\s*]+`?([^|\n`]+)'
    ]:
        m_c = re.search(p_cl, md_content, re.IGNORECASE)
        if m_c and m_c.group(1).strip() and not m_c.group(1).strip().lower().startswith(('remediation', 'plan', 'assessment', 'id:')):
            detected_client = strip_all_markdown_and_emojis(m_c.group(1))
            break
    if not detected_client:
        detected_client = "Client_Application_v1.0"

    findings = extract_audit_findings_matrix(md_content, jurisdiction=jurisdiction, framework=framework)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#1E3A8A'),
        spaceAfter=3
    )
    sub_style = ParagraphStyle(
        'ReportSub',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=13,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=12
    )
    h2_style = ParagraphStyle(
        'Heading2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=colors.HexColor('#1E3A8A'),
        spaceBefore=10,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor('#1E293B')
    )
    bold_style = ParagraphStyle(
        'BodyBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor('#1E293B')
    )
    th_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.white,
        alignment=0
    )
    
    status_styles = {
        'Fully Compliant': ParagraphStyle('StComp', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#166534')),
        'Partially Compliant': ParagraphStyle('StPart', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#854D0E')),
        'Not Compliant': ParagraphStyle('StNot', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#991B1B')),
        'Not Applicable': ParagraphStyle('StNA', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#475569')),
        'Untested': ParagraphStyle('StUnt', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor('#475569')),
    }

    elements = []

    # Title Banner
    elements.append(Paragraph("COMPLIANCE ASSESSMENT REPORT", title_style))
    elements.append(Paragraph("Standardized Regulatory & Technical Audit Report", sub_style))

    # Table 1: Metadata Card (Width = 720 pt)
    meta_data = [
        [Paragraph("Client / Target Application", bold_style), Paragraph(detected_client, body_style)],
        [Paragraph("Regulatory Standard / Framework", bold_style), Paragraph(detected_fw, body_style)],
        [Paragraph("Audit Generation Timestamp (UTC)", bold_style), Paragraph(datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"), body_style)],
        [Paragraph("Assessor & Verification", bold_style), Paragraph("ComplianceMesh Multi-Agent Pipeline | Verified (Nemotron 3 Ultra)", body_style)],
    ]
    t_meta = Table(meta_data, colWidths=[200, 520])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#FFFFFF')),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_meta)
    elements.append(Spacer(1, 10))

    # Executive Summary Section
    elements.append(Paragraph("1. Executive Summary", h2_style))
    m_exec = re.search(r'(?:#{1,4}\s*Executive Summary|\*\*Executive Summary\*\*)\s*\n+([\s\S]+?)(?:\n#{1,4}|\n---|\Z)', md_content, re.IGNORECASE)
    exec_summary = m_exec.group(1).strip() if m_exec else f"Automated compliance assessment completed against {detected_fw} baseline."
    clean_exec = strip_all_markdown_and_emojis(exec_summary)
    elements.append(Paragraph(clean_exec, body_style))
    elements.append(Spacer(1, 10))

    # Table 2: Executive Compliance Scorecard (No Emojis)
    elements.append(Paragraph("2. Executive Compliance Scorecard", h2_style))
    cnt_f = sum(1 for f in findings if 'Fully' in f['status'])
    cnt_p = sum(1 for f in findings if 'Partially' in f['status'])
    cnt_n = sum(1 for f in findings if 'Not' in f['status'])
    cnt_na = sum(1 for f in findings if any(k in f['status'].lower() for k in ['applicable', 'untested', 'pre-implementation', 'design']))
    tot_assess = cnt_f + cnt_p + cnt_n
    
    pct_f = f"{(cnt_f / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"
    pct_p = f"{(cnt_p / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"
    pct_n = f"{(cnt_n / tot_assess * 100):.1f}%" if tot_assess > 0 else "0.0%"

    score_data = [
        [Paragraph("Compliance Status", th_style), Paragraph("Count", th_style), Paragraph("% of Assessable", th_style)],
        [Paragraph("Fully Compliant", status_styles['Fully Compliant']), Paragraph(str(cnt_f), bold_style), Paragraph(pct_f, body_style)],
        [Paragraph("Partially Compliant", status_styles['Partially Compliant']), Paragraph(str(cnt_p), bold_style), Paragraph(pct_p, body_style)],
        [Paragraph("Not Compliant", status_styles['Not Compliant']), Paragraph(str(cnt_n), bold_style), Paragraph(pct_n, body_style)],
        [Paragraph("Evaluated Scope Items / Not Applicable", status_styles['Not Applicable']), Paragraph(str(cnt_na), bold_style), Paragraph("—", body_style)],
    ]
    t_score = Table(score_data, colWidths=[260, 160, 300])
    t_score.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_score)
    elements.append(Spacer(1, 14))

    # Table 3: Technical Control Assessment Matrix (6 Columns, Width = 720 pt)
    elements.append(Paragraph("3. Technical Control Assessment Matrix", h2_style))
    matrix_headers = [
        Paragraph("Control ID", th_style),
        Paragraph("Requirement Description", th_style),
        Paragraph("Compliance Status", th_style),
        Paragraph("Auditor Finding & Rationale", th_style),
        Paragraph("Recommended Remediation", th_style),
        Paragraph("Priority", th_style)
    ]
    matrix_data = [matrix_headers]

    for f in findings:
        st_val = f['status']
        st_style = status_styles.get(st_val, body_style)
        matrix_data.append([
            Paragraph(f['control_id'], bold_style),
            Paragraph(f['title'], body_style),
            Paragraph(st_val, st_style),
            Paragraph(f['rationale'], body_style),
            Paragraph(f['remediation'], body_style),
            Paragraph(f['priority'], body_style)
        ])

    # Widths: 80 + 110 + 90 + 210 + 160 + 70 = 720 pt
    t_matrix = Table(matrix_data, colWidths=[80, 110, 90, 210, 160, 70], repeatRows=1)
    t_matrix_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]
    for r_idx in range(1, len(matrix_data)):
        bg = colors.HexColor('#F8FAFC') if r_idx % 2 == 0 else colors.HexColor('#FFFFFF')
        t_matrix_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), bg))
    t_matrix.setStyle(TableStyle(t_matrix_style))
    elements.append(t_matrix)
    elements.append(Spacer(1, 14))

    # Table 4: Actionable Remediation Roadmap (Width = 720 pt)
    elements.append(Paragraph("4. Actionable Remediation Roadmap", h2_style))
    p0_list = [f['control_id'] for f in findings if 'P0' in f.get('priority', '') or 'Not Compliant' in f.get('status', '')]
    p1_list = [f['control_id'] for f in findings if 'P1' in f.get('priority', '') or 'Partially Compliant' in f.get('status', '')]
    p2_list = [f['control_id'] for f in findings if 'P2' in f.get('priority', '') or 'Not Applicable' in f.get('status', '') or 'Untested' in f.get('status', '')]

    road_data = [
        [Paragraph("Priority Tier", th_style), Paragraph("Target Controls Affected", th_style), Paragraph("Engineering Milestone & Action", th_style)],
        [Paragraph("P0 (Immediate / 0–14 Days)", bold_style), Paragraph(", ".join(p0_list) if p0_list else "None", body_style), Paragraph("Remediate critical security gaps and enforce baseline protections.", body_style)],
        [Paragraph("P1 (Near-Term / 30 Days)", bold_style), Paragraph(", ".join(p1_list) if p1_list else "None", body_style), Paragraph("Implement multi-factor authentication, monitoring, and audit logging.", body_style)],
        [Paragraph("P2 (Long-Term / 60 Days)", bold_style), Paragraph(", ".join(p2_list) if p2_list else "None", body_style), Paragraph("Formalize governance policies, vendor assessments, and review cycles.", body_style)],
    ]
    t_road = Table(road_data, colWidths=[160, 200, 360])
    t_road.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#FFFFFF'), colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_road)
    elements.append(Spacer(1, 14))

    # 5. Verification Sign-Off
    elements.append(Paragraph("5. Verification & Auditor Sign-Off", h2_style))
    elements.append(Paragraph(
        "This compliance audit artifact was synthesized by the ComplianceMesh Multi-Agent Pipeline and verified against statutory ground-truth catalogs. "
        "All cited findings were extracted from active source code, container configurations, and runtime security probes.",
        body_style
    ))

    doc.build(elements, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


def export_pdf(md_content: str, jurisdiction: str = "nist", framework: str = "csf", output_path: str = None) -> bytes:
    """
    Exports a Markdown report to a publication-grade PDF.
    """
    pdf_bytes = render_pdf_report_bytes(md_content, jurisdiction=jurisdiction, framework=framework)
    if output_path:
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
    return pdf_bytes


def extract_target_entity_name(md_content: str, fallback: str = "Client_App") -> str:
    """
    Extracts the clean repository name, zip file name, or organization name from report content.
    e.g. 'https://github.com/fleetbase/fleetbase' -> 'fleetbase'
         'my_project.zip' -> 'my_project'
         'Acme Corp' -> 'Acme_Corp'
    """
    # 1. Search for explicit key-value pairs with colon
    for pattern in [
        r'(?:Repository\s+Target|Target\s+Repository|Repository|Repo)\s*:\s*`?([^|\n`]+)',
        r'(?:Zip\s+File|Uploaded\s+File|Source\s+Archive|Target\s+Archive|Source\s+Code\s+Archive|Archive|Source|Target)\s*:\s*`?([^|\n`]+)',
        r'(?:Organization|Org\s+Name|Company|Client\s+ID|Platform|Target\s+Application|System|Client)\s*:\s*`?([^|\n`]+)',
    ]:
        m = re.search(pattern, md_content, re.IGNORECASE)
        if m and m.group(1).strip():
            raw_val = m.group(1).strip().strip('*').strip('`').strip()
            if not raw_val.lower().startswith(('remediation', 'plan', 'assessment', 'id:', 'scan', 'details', 'baseline', 'standard')):
                if "github.com" in raw_val or ("/" in raw_val and not raw_val.startswith("/")):
                    clean_val = raw_val.rstrip("/").split("/")[-1].replace(".git", "")
                    if clean_val:
                        return re.sub(r'[^A-Za-z0-9_\-]', '_', clean_val)
                if any(ext in raw_val.lower() for ext in ['.zip', '.tar.gz', '.tgz', '.tar']):
                    m_f = re.search(r'([A-Za-z0-9_\-]+)\.(?:zip|tar\.gz|tgz|tar)', raw_val, re.IGNORECASE)
                    if m_f:
                        return m_f.group(1)
                clean_val = re.sub(r'[^A-Za-z0-9_\- ]', '', raw_val).strip().replace(" ", "_")
                if clean_val and clean_val.lower() not in ["none", "n/a", "unknown"]:
                    return clean_val
    
    # 2. Search for any .zip filename in the header lines
    m_zip = re.search(r'([A-Za-z0-9_\-]+)\.(?:zip|tar\.gz|tgz|tar)', md_content[:2000], re.IGNORECASE)
    if m_zip:
        return m_zip.group(1)
        
    # 3. Search for any github repo in the header lines
    m_git = re.search(r'github\.com/[A-Za-z0-9_\-]+/([A-Za-z0-9_\-]+)', md_content[:2000], re.IGNORECASE)
    if m_git:
        return m_git.group(1)

    return fallback


def export_docx(md_content: str, jurisdiction: str = "nist", framework: str = "csf", output_path: str = None) -> bytes:
    """
    Exports a Markdown report to an executive Word (.docx) document.
    """
    docx_bytes = render_template_docx_bytes(md_content, jurisdiction=jurisdiction, framework=framework)
    if output_path:
        with open(output_path, "wb") as f:
            f.write(docx_bytes)
    return docx_bytes


def export_report(
    md_content: str,
    jurisdiction: str,
    framework: str,
    output_format: str,
    output_dir: str | None = None,
) -> str:
    """
    Exports a Markdown report to the specified format.

    Args:
        md_content: The Markdown report content.
        jurisdiction: e.g. "nist", "eu".
        framework: e.g. "csf", "gdpr".
        output_format: One of "html", "json", "txt", "docx", "pdf".
        output_dir: Output directory (defaults to REPORTS_DIR).

    Returns:
        Path to the exported file.
    """
    output_dir = output_dir or REPORTS_DIR
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    target_name = extract_target_entity_name(md_content, fallback=f"{jurisdiction}_{framework}")
    base_name = f"The_Audit_Report_of_{target_name}_{framework}_{timestamp}"

    if output_format == "pdf":
        out_path = os.path.join(output_dir, f"{base_name}.pdf")
        export_pdf(md_content, jurisdiction, framework, out_path)

    elif output_format == "docx":
        out_path = os.path.join(output_dir, f"{base_name}.docx")
        export_docx(md_content, jurisdiction, framework, out_path)

    elif output_format == "html":
        title = f"Compliance Report — {jurisdiction.upper()} / {framework.upper()}"
        body = markdown_to_html(md_content)
        content = HTML_TEMPLATE.format(
            title=html.escape(title),
            body=body,
            export_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
        out_path = os.path.join(output_dir, f"{base_name}.html")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

    elif output_format == "json":
        data = markdown_to_json(md_content, jurisdiction, framework)
        out_path = os.path.join(output_dir, f"{base_name}.json")
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    elif output_format == "txt":
        content = markdown_to_text(md_content)
        out_path = os.path.join(output_dir, f"{base_name}.txt")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

    elif output_format == "docx":
        out_path = os.path.join(output_dir, f"{base_name}.docx")
        export_docx(md_content, jurisdiction, framework, out_path)

    else:
        raise ValueError(f"Unsupported format: '{output_format}'. Use 'html', 'json', 'txt', or 'docx'.")

    # Log export
    try:
        import pipeline_logger
        pipeline_logger.log_info(
            "report_export",
            f"Exported {output_format.upper()} report: {out_path}",
            extra={"format": output_format, "path": out_path},
        )
    except ImportError:
        pass

    return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Multi-Format Report Exporter")
    parser.add_argument(
        "--framework", required=True,
        help="Jurisdiction/framework slug, e.g. 'nist/csf' or 'eu/gdpr'"
    )
    parser.add_argument(
        "--format", required=True, choices=["html", "json", "txt", "all"],
        help="Output format: html, json, txt, or all"
    )
    parser.add_argument(
        "--input", default=None,
        help="Path to a specific Markdown report file (auto-detected if omitted)"
    )
    args = parser.parse_args()

    jurisdiction, framework = args.framework.split("/")

    if args.input:
        md_path = args.input
    else:
        md_path = find_latest_report(jurisdiction, framework)
        if not md_path:
            print(f"No Markdown report found for {jurisdiction}/{framework} in '{REPORTS_DIR}/'.")
            print("Run Agent 5 first, or specify --input path.")
            return

    print(f"Source report: {md_path}")
    with open(md_path, encoding="utf-8-sig") as f:
        md_content = f.read()

    formats = ["html", "json", "txt"] if args.format == "all" else [args.format]

    for fmt in formats:
        out_path = export_report(md_content, jurisdiction, framework, fmt)
        print(f"  Exported {fmt.upper():>4} → {out_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
